### ISSUE TITLE
ES6: as, from and template strings syntax highlight

### ISSUE THREAD

**Issue by fundon** [atom/language-javascript#107]
I choose the `Atom Dark` theme, template strings' variable are highlighted.
I tested, the `monokai` and `solarized dark` do not highlight.

**Comment by AMalininHere** [comment]
You can just use https://atom.io/packages/language-javascript-better

**Comment by lee-dohm** [comment]
@fundon it sounds like you should be filing this bug on the monokai and solarized dark themes, not on the language package itself. If it highlights as expected on any syntax theme, then the language package is correct.

**Comment by fundon** [comment]
Thanks.
