### ISSUE TITLE
Recognize Arrow functions

### ISSUE THREAD

**Issue by burabure** [atom/language-javascript#109]
Arrow functions aren't recognized by the language parse, so they can't get highlighted.

```javascript
() => {
 ...
}
```

**Comment by AMalininHere** [comment]
You can just use https://atom.io/packages/language-javascript-better

**Comment by burabure** [comment]
Thanks @AMalininHere 

Standard syntax should be included in the standard language package anyways; but it's nice to have another package meanwhile

**Comment by AMalininHere** [comment]
In this case, you can take part in [mine issue](https://github.com/atom/language-javascript/issues/117)

**Comment by AMalininHere** [comment]
I think that it's fixed [here](https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L315)

**Comment by kevinsawicki** [comment]
Fixed by #139
