### ISSUE TITLE
JavaScript syntax highlight is broken

### ISSUE THREAD

**Issue by 50Wliu** [atom/language-javascript#110]
_From @alexandernst on March 3, 2015 22:56_

Screenshot: http://imagebin.ca/v/1tb6MvP8FZ6I

Code so you can test:

    /***
     * @method assign(<obj1>, <obj2>, ...)
     * @returns String
     * @short Assigns variables to tokens in a string, demarcated with `{}`.
     * @extra If an object is passed, it's properties can be assigned using the object's keys (i.e. {name}). If a non-object (string, number, etc.) is passed it can be accessed by the argument number beginning with {1} (as with regex tokens). Multiple objects can be passed and will be merged together (original objects are unaffected).
     * @example
     *
     *   'Welcome, Mr. {name}.'.assign({ name: 'Franklin' })   -> 'Welcome, Mr. Franklin.'
     *   'You are {1} years old today.'.assign(14)             -> 'You are 14 years old today.'
     *   '{n} and {r}'.assign({ n: 'Cheech' }, { r: 'Chong' }) -> 'Cheech and Chong'
     *
     ***/
    'assign': function() {
      var assign = {};
      flattenedArgs(arguments, function(a, i) {
        if(isObjectType(a)) {
          simpleMerge(assign, a);
        } else {
          assign[i + 1] = a;
        }
      });
      return this.replace(/\{([^{]+?)\}/g, function(m, key) {
        return hasOwnProperty(assign, key) ? assign[key] : m;
      });
    }

  });

_Copied from original issue: atom/atom#5829_

**Comment by alexandernst** [comment]
Just to make sure the bug is reproducible even if the image is erased:

Remove the "'" from `...If an object is passed, it's properties ca...` and the codoe will be highlighted correctly. Uno de change and the highlighting will break.

**Comment by braver** [comment]
I can't reproduce this, it's fine as is:
![screen shot 2015-03-27 at 19 50 46](https://cloud.githubusercontent.com/assets/2543659/6874840/aafb6150-d4ba-11e4-9885-597492c355db.png)

**Comment by 50Wliu** [comment]
Assuming fixed, closing.

**Comment by MatthewMueller** [comment]
Running into this on `Atom 0.188.0`:

![img](https://cldup.com/Dfv8roryKO.png)

**Comment by 50Wliu** [comment]
Your bug seems different.  It isn't being caused by single quotes being present within the comment block.

**Comment by MatthewMueller** [comment]
Ahh, my bad. Didn't read close enough.
