### ISSUE TITLE
ECMAScript 2015

### ISSUE THREAD

**Issue by gyzerok** [atom/language-javascript#115]
Requesting to add correct support for upcoming ECMAScript syntax.
For example:
```javascript
var foo = {
  bar: function () {}, // old way, correct support
  baz() {} // new way, incorrect support
};
```

https://github.com/jesseweed/seti-syntax/issues/63

**Comment by nelix** [comment]
There is a sublime package this work could be based on: https://github.com/babel/babel-sublime
Its really really good, and it makes me want to use sublime :(

**Comment by roman01la** [comment]
+1

**Comment by kiwiupover** [comment]
:+1:

**Comment by AMalininHere** [comment]
You can just use my active supported repo https://github.com/AMalininHere/language-javascript-better

**Comment by mattdeboard** [comment]
Unfortunately language-javascript-better doesn't really play nice with this (I tried). It would be much better if you could submit the ES6 support you've implemented as a patch to this project, IMO.

**Comment by rossPatton** [comment]
^ I agree. I can understand having separate packages for things like jsx or flow, but ES2015 is the official spec now. We shouldn't need to install javascript-better or language-babel to get es6 support.

**Comment by tomByrer** [comment]
Also please include the methods for the new 'standard objects': [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Methods), Map, WeakSet, WeakMap.
`add` highlights already, `delete` does not.

**Comment by Zirro** [comment]
With much of ES6 now supported, I believe this issue could be closed and remaining features discussed in separate issues.

**Comment by 50Wliu** [comment]
Thanks @Zirro.  The original example also seems to be highlighting correctly now.
