### ISSUE TITLE
Merge with languale-javascript-better

### ISSUE THREAD

**Issue by AMalininHere** [atom/language-javascript#117]
Hello.
May be we will merge [language-javascript](https://github.com/atom/language-javascript) and [language-javascript-better](https://github.com/AMalininHere/language-javascript-better)?

**Comment by burabure** [comment]
+1 haven't reviewed the code, but we need this on the language package.

**Comment by thomasjo** [comment]
I suggest you open pull requests with enhancements instead. What you're suggesting is unlikely to happen in my opinion.

**Comment by AMalininHere** [comment]
I just need write access.
You can just compare activity:
https://github.com/AMalininHere/language-javascript-better/graphs/contributors
https://github.com/atom/language-javascript/graphs/contributors

**Comment by kevinsawicki** [comment]
> I just need write access.

You should now have write access to this repository.

So I'm going to close this out and we can just discuss merging in changes in pull requests, thanks for reaching out and offering to help out :+1:
