### ISSUE TITLE
Broken syntax highlighting with single quotes

### ISSUE THREAD

**Issue by YuriSolovyov** [atom/language-javascript#127]
Single quotes
![screenshot from 2015-04-02 11 41 42](https://cloud.githubusercontent.com/assets/2168518/6960832/c0655fd2-d92e-11e4-8f42-d98bf7c4c3d4.png)
Double quotes
![screenshot from 2015-04-02 11 46 43](https://cloud.githubusercontent.com/assets/2168518/6960833/c0689aee-d92e-11e4-8a00-81db47be8d52.png)

Code:
``` javascript
destroy_panels: function() {
    var self = this;
    self.panels_root.find('.booking_panel').filter(':not(#booking_panel_ledgers)').remove();
},

clear_panels: function() {
    var self = dm_doc_booking_panel;
    var ledgers_table = self.ledgers_table;

    _.each(self.panels, function(panel) {
        if (!panel.enabled) { return; }
        panel.pages_container.empty();
        panel.ledger_selector.find('.ledger_row').remove();
    });

    ledgers_table.find('.input_row').remove();
    ledgers_table.find('.amount_total').html('');
    ledgers_table.find('.split_total').html('');
    ledgers_table.find('.vat_total').html('');
},
```

**Comment by EloB** [comment]
It has something todo with the `:not`.

**Comment by YuriSolovyov** [comment]
Wow, seems like Github's code highlighter can't handle that too :)

**Comment by JixunMoe** [comment]
Same here, it breaks when the line contains has `:`, `(` and a `)` in the string.  
For both single and double quote.

```js
// comment

var x = ({
  a: foo(')')
});

// comment
```

**Comment by EloB** [comment]
When will this be included in atom? Because I still have the problem...

**Comment by 50Wliu** [comment]
This will be in the next Atom release, 0.190.0.
