### ISSUE TITLE
import ended by newline breaks syntax highlighting

### ISSUE THREAD

**Issue by AluisioASG** [atom/language-javascript#128]
It seems that 2902c4a breaks highlighting after an ASI-relying import:
```js
import x
let y
```
The `let` keyword isn't highlighted.  Quotes inside comments are considered to open strings.

**Comment by kevinsawicki** [comment]
Could you elaborate on what you mean by "ASI-relying import"?

**Comment by AluisioASG** [comment]
![image](https://cloud.githubusercontent.com/assets/1904165/7016747/261fb5ee-dcc1-11e4-80f5-606ca27a3a56.png)

**Comment by kevinsawicki** [comment]
Fixed by #135
