### ISSUE TITLE
JSDoc/YUIDoc styling

### ISSUE THREAD

**Issue by balupton** [atom/language-javascript#130]
https://discuss.atom.io/t/jsdoc-yuidoc-syntax-highlighting/15934
https://github.com/nylki/pen-paper-coffee-syntax/issues/14

**Comment by AMalininHere** [comment]
JSDoc ready to use

**Comment by AMalininHere** [comment]
YUIdoc ready to use

**Comment by balupton** [comment]
Nothing happening for me:

![screenshot 2015-05-01 01 43 26](https://cloud.githubusercontent.com/assets/61148/7418832/8872deac-efa3-11e4-8978-2c34f3247586.png)

language-javascript v0.76.0

pen-paper-coffee-syntax v0.8.3

perhaps YUIdoc changes haven't been released despite being committed?

**Comment by mnquintana** [comment]
@balupton There hasn't been a release yet with these changes - should be coming soon.
