### ISSUE TITLE
String-related highlighting error

### ISSUE THREAD

**Issue by cvrebert** [atom/language-javascript#142]
The highlighting in https://github.com/twbs/bootlint/blob/9f9ac92ea1288fb1af5f281d924aa3abd1c7770f/src/bootlint.js#L603 goes wrong starting on line 604.
(GitHub is currently using v0.72 of this project for its JS syntax highlighting; see https://github.com/github/linguist/tree/master/vendor/grammars )

**Comment by lee-dohm** [comment]
Are you reporting an issue for Atom the editor, which doesn't use linguist for its syntax highlighting, or GitHub the website, which does? If you're reporting an issue with Atom, what do you mean by "goes wrong"?

Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?

**Comment by mnquintana** [comment]
@lee-dohm Linguist uses Atom's language-javascript for its syntax highlighting just like Atom does, so if there is a syntax highlighting bug on GitHub then it exists in this package.

**Comment by cvrebert** [comment]
I am observing the issue in GitHub.

**Comment by cvrebert** [comment]
Seems similar to #127.

**Comment by lee-dohm** [comment]
Ah ok ... thanks @mnquintana! I didn't know they had started doing that :grinning:

**Comment by mnquintana** [comment]
I can't reproduce this in Atom 0.195.0-14161a6 with that file and the JS grammar, which makes me think linguist needs an update.

**Comment by pchaigno** [comment]
@mnquintana Are you able to reproduce it with version 0.72 of this grammar? GitHub doesn't use the same regex engine as Atom so sometimes errors can happen in GitHub and not happen in Atom.

**Comment by 50Wliu** [comment]
@pchaigno Linguist does use `language-javascript` to parse Github.com syntax.

**Comment by pchaigno** [comment]
@50Wliu np. I think #143 should fix this. Have tested it yet though.
