### ISSUE TITLE
github: syntax highlighting breaks on import without a semicolon

### ISSUE THREAD

**Issue by queckezz** [atom/language-javascript#144]
As far I can see [github/linguist](https://github.com/github/linguist) is using this project to highlight the given javascript on the github site. 

Right now the syntax highlighting breaks on an `import` statement without a semicolon:
```js
import { x } from './test'

var x = true
//^ No syntax highlighting
```

```js
import { x } from './test';

var x = true
//^ Syntax highlighting
```

Couple of examples:
https://github.com/transduce/transduce/blob/master/src/async.js
https://github.com/segmentio/deku/blob/master/examples/events/index.js

Just wanted to report this, if I have time I'll do a pull request.

**Comment by AMalininHere** [comment]
Issue #128 
Already fixed.
