### ISSUE TITLE
ES6 highlighting bug

### ISSUE THREAD

**Issue by bucaran** [atom/language-javascript#150]
There is definitely a bug in the syntax highlighting:

With semicolon:

```js
import stuff from "library" ; // <=== The culprit!

class Color { /* Yay! But I don't like semicolons! */}
```

Without semicolon:
```js
import stuff from "library"

class BlackAndWhite { /* So, sad! */}
```

This is a bummer to me because I don't like to use semicolons in my JS code.

**Comment by AMalininHere** [comment]
Fixed by #135

**Comment by bucaran** [comment]
Well, it's not fixed here in this page...

**Comment by 50Wliu** [comment]
What Atom version are you running, @bucaran?

**Comment by bucaran** [comment]
@50Wliu My Atom is OK. The problem is here on GitHub when you browse code or when displaying Markdown as you can see above, or in the picture I kindly put together for your clear understanding. 

![untitled](https://cloud.githubusercontent.com/assets/8317250/7637369/720d75a4-faa8-11e4-9c85-75aa5b924dcb.png)

**Comment by mnquintana** [comment]
@bucaran So you only see this with GitHub's syntax highlighting, and not Atom's anymore?

**Comment by bucaran** [comment]
Fortunately I never presented this problem in Atom. Only on GitHub. 

Actually I opened this issue first at github.com/github/linguist/issues/2398, but was suggested to submit here, so I did.

**Comment by mnquintana** [comment]
Alright, thanks for the updates @bucaran! It looks like linguist just needs to update the version of language-javascript they're using, so I'm going to close this one.

**Comment by bucaran** [comment]
Thanks! :+1:
