### ISSUE TITLE
Missing scopes

### ISSUE THREAD

**Issue by bobrocke** [atom/language-javascript#152]
Here are some examples:

![open-a-terminal - atom](https://cloud.githubusercontent.com/assets/2962426/7798483/62933168-02c8-11e5-8233-ae83ebad15a8.jpg)

But there are many others. This grammar appears to be pretty young.

**Comment by izuzak** [comment]
Thanks for pointing them out -- can you add this as a comment to https://github.com/atom/language-javascript/issues/137 which is already tracking missing scopes?
