### ISSUE TITLE
Iconsistent syntax highlighting with HTML/Angular documents.

### ISSUE THREAD

**Issue by smlombardi** [atom/language-javascript#157]
Why does the new syntax hghlighting for Angular JS (especially as attributes) work in some places but not others?

See below:
![3422375190fbd762d327577c6eca67a1a657b990_690x204](https://cloud.githubusercontent.com/assets/835148/7960612/ec67490c-09cf-11e5-8713-ae48320299b4.png)

The top-most ng-click scopes as:
![45a800e2687a6d1a2801a41162c2865ab6fc90c8](https://cloud.githubusercontent.com/assets/835148/7960619/f604144a-09cf-11e5-92f7-3d339db74d05.png)

But the one in the LI is 
![c68fabcc104829140e76cb4ab54cca40a9d5253f](https://cloud.githubusercontent.com/assets/835148/7960627/040a5f0e-09d0-11e5-92bd-268bdc5f1e88.png)

**Comment by mnquintana** [comment]
@smlombardi I don't think the Angular support is provided by this package (or any package that ships with Atom).

**Comment by smlombardi** [comment]
It was added in .200. Suddenly all my documents were type "html/angular"
and the new coloring appeared.

**Comment by Victorystick** [comment]
I think this ought to be an issue in lanuage-html.

**Comment by smlombardi** [comment]
They sent me here.

**Comment by kevinsawicki** [comment]
Looks like this was fixed in the angular package via https://github.com/angular-ui/AngularJS-Atom/issues/42
