### ISSUE TITLE
JavaScript highlighting handles single-line comments incorrectly

### ISSUE THREAD

**Issue by Narthur** [atom/language-javascript#159]
Highlights everything following a single-line comment as if it is part of the comment.

Example:
https://github.com/OuachitaHillsMinistries/ohc-handbook-md2id/blob/master/markdownID.jsx

**Comment by mnquintana** [comment]
[This package doesn't handle JSX files](https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L2-L11), so this must be coming from a community package you have installed - can you post a list of your installed packages? (`apm list --installed`)

**Comment by Narthur** [comment]
I'm sorry, I should have explained. This is occurring within the GitHub interface. GitHub support sent me to github/linguist, which then sent me here.

**Comment by 50Wliu** [comment]
I can't reproduce this, at least in Atom - I tried copy/pasting your entire file in and it renders fine.  Just as a quick experiment - if you change the file extension to `.js`, does that make the file render correctly?  Thanks.

**Comment by 50Wliu** [comment]
I just tried adding it as a Gist, but everything still highlights correctly :confused:.

**Comment by Narthur** [comment]
Ok, that is really odd. I viewed my file on GitHub--syntax highlighting still not working. Renamed it .js, syntax highlighting started working. Renamed it back to .jsx, syntax highlighting continued to work. Any idea what might cause this behavior?

**Comment by lee-dohm** [comment]
> Any idea what might cause this behavior?

It could be that there was a cache that needed to be refreshed and the double-rename took care of that step. I'm glad it is working for you now. Do you mind if we close the Issue?

**Comment by Narthur** [comment]
We can close the issue. I do hope, though, that someone will catch it if it's more than a fluke.
