### ISSUE TITLE
`const` with destructuring assignment isn't highlighted

### ISSUE THREAD

**Issue by impinball** [atom/language-javascript#160]
In Atom v0.207.0, plugin v0.78.0, I have encountered this problem (it's valid ES 2015):

![image](https://cloud.githubusercontent.com/assets/4483844/8270589/2e04eb48-17b4-11e5-937a-4a87cbdcf560.png)

That `const` should be styled as `storage.modifier.js`, not unstyled.

**Comment by izuzak** [comment]
Please add a comment about this to https://github.com/atom/language-javascript/issues/115, which is a more general issue.

**Comment by Victorystick** [comment]
This has been addressed by #174. Beyond making `const` highlight, `line`, `column` and `file` are properly marked as constants. (A fix for a regex regression in 0.82 (#176) is also inbound #177).
