### ISSUE TITLE
Provide means to separate non-alpha-numeric keywords from the rest 

### ISSUE THREAD

**Issue by eldargab** [atom/language-javascript#162]
So that we could highlight  `+`, `-`, etc like a normal text.

**Comment by 50Wliu** [comment]
@eldargab Is this still an issue in Atom 1.1.0?  If so, can you please see if #225 solved your issue?  Thanks!

**Comment by 50Wliu** [comment]
No response, assuming resolved.  Feel free to comment here if it's still an issue.
