### ISSUE TITLE
Recognise "@mixins" doc block tag

### ISSUE THREAD

**Issue by Krinkle** [atom/language-javascript#164]
In [JSDuck](https://github.com/senchalabs/jsduck), `@mixins {Identifier}` is used to indicate which classes' methods have been mixed into the current class' prototype.

It seems `@mixin` is already recognised, but that's not recognised in JSDuck. And mixin might also be reserved for the purpose of indicating a class is itself a mixin (as opposed to having mixed in a class). 

<img width="212" src="https://cloud.githubusercontent.com/assets/156867/8445484/c129b7d0-1f95-11e5-8e3e-cfc19a5c09d1.png" title="Screen shot of Atom editor" />

**Comment by 50Wliu** [comment]
Closed by #165.
