### ISSUE TITLE
const in brackets causes syntax highlighting issues

### ISSUE THREAD

**Issue by petemill** [atom/language-javascript#180]
When writing a `const` variable (inside some brackets), atom continues to think all the characters afterwards are still part of that variable's name, until it reaches some kind of marker, usually an `=`.

This seems to be a new bug introduced in Atom 1.0.3 as I had not experienced it prior, using the same code.

Examples of problematic code:
```js
for (const myVar of myArray) {
  //do something
}
```
```js
if (const myVar === undefined) 
  let str = 'I am the wrong color!';
```
```js
(const myVar);
window.alert("Atom still think's I'm a const!");
```

This works fine:
```js
const myVar;
//atom knows I'm no longer a const ♥

**Comment by 50Wliu** [comment]
@petemill you're right to say that it only fixes itself when an `=` is encountered: https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L370

**Comment by Victorystick** [comment]
I'll get on this. I didn't think of for-in/for-of loops.
