### ISSUE TITLE
JavaScript is broken 

### ISSUE THREAD

**Issue by bucaran** [atom/language-javascript#183]
Hi. JavaScript the syntax highlighting is broken and this is affecting me in both Atom and GitHub code viewer. Please see the attached images.

![untitled 2](https://cloud.githubusercontent.com/assets/8317250/9020487/9b1bffa4-3849-11e5-99f0-1d51ba9ecdf1.png)
![untitled](https://cloud.githubusercontent.com/assets/8317250/9020488/9c83db8c-3849-11e5-8512-05e7754326a0.png)

https://github.com/github/linguist/issues/2530

**Comment by bucaran** [comment]
linguist/issues/2530

**Comment by 50Wliu** [comment]
Looks like another case where strings aren't given enough priority.

**Comment by bucaran** [comment]
Fortunately, `const` now works properly when using the destructuring syntax. This was failing a few weeks ago, but I was too lazy to report it.

```js
const { a, b } = f()
```

Having said this, `const` is still broken in the following case:

```js
export function* find (path, hook = _ => _) {
  const root = join(process.cwd(), path)
  return hook((yield fs.stat(path))
    .isDirectory() ? yield resolve(root) : root)
  function* resolve (root) {
    for (const file of function* () {
      for (const ext of Object.keys(jsVariants))
        for (const name of ["Flyfile", "flyfile"])
          yield join(root, `${name}${ext}`)
    }()) try { if (yield fs.stat(file)) return file } catch (_) {}
    throw { code: "ENOENT" }
  }
}
```

**Comment by 50Wliu** [comment]
Yeah, that's been fixed - Linguist just needs to update to a commit that has it.

**Comment by 50Wliu** [comment]
Interestingly, putting the bracket on a newline fixes the issue...

**Comment by bucaran** [comment]
:sob:

**Comment by bucaran** [comment]
Another one that has been broken for a while, which I also forgot to report is when using default parameters:

```js
export function filter (pkg, load, blacklist = [], bind = "oh la la!") {
...
}
```

**Comment by 50Wliu** [comment]
Yeah, I'm looking at the function-params regex, and it's pretty basic.
