### ISSUE TITLE
`constructor` is no longer highlighted

### ISSUE THREAD

**Issue by mnquintana** [atom/language-javascript#191]
Although `constructor` is tokenized correctly, it now has no highlighting (in One Dark Syntax) as of Atom 1.0.4.

#### Example

```js
class Overlay {
  constructor(map) {
    this.map = map;
  }

  getMap() {
    return this.map;
  }
}
```

My guess is that this has something to do with https://github.com/atom/language-javascript/pull/184.

/cc @50Wliu

**Comment by 50Wliu** [comment]
This is because one-dark doesn't generically color `.entity` (which would cover `.entity.name.constructor` and `.entity.name.function`, which is also used a lot), only `.entity.name.type` and `.entity.other.inherited-class`.
/cc @simurai

**Comment by simurai** [comment]
Coloring only `.entity` would affect other places.. for example in CSS the `::` in `::before`.

We could add `.entity.name.constructor`?

1. Should it look the same as the `getMap()` function?
2. Do other languages also define a `.entity.name.constructor` or is that only in JavaScript?

**Comment by mnquintana** [comment]
Maybe it could also have `.entity.name.function` too?

**Comment by 50Wliu** [comment]
I'm definitely open to a name change :smile:.  Don't have much experience with how to properly name these things.

**Comment by Victorystick** [comment]
How do languages like Java, C etc. manage their constructors? Should JS do something similar?

**Comment by 50Wliu** [comment]
When #146 gets updated (I'm working on that right now), we'll also have `.entity.name.property`.  What about adding `.entity.name` instead of just `.entity`?

**Comment by MaximSokolov** [comment]
> Perhaps **entity.name.function.constructor** would work? Its syntax pretty much like any function (or method).

:+1:

**Comment by 50Wliu** [comment]
Wow, I just keep forgetting to push my branch that fixes this to Github...PR'ing in a moment.
