### ISSUE TITLE
Arrow functions with a single param as default arguments to functions

### ISSUE THREAD

**Issue by bucaran** [atom/language-javascript#193]
```js
// incorrect highlighting - arrow isn't highlighted
function f (a = _ => _) { }
function f (a = arg => arg) { }
function f (a = ret => ret) { }
function f (a = pchaigno => pchaigno) { }

// correct highlighting - arrow is highlighted
function f (a = (_) => _) { }
function f (a = (arg) => arg) { }
function f (a = (ret) => ret) { }
function f (a = (pchaigno) => pchaigno) { }
```

**Comment by pchaigno** [comment]
@bucaran Is it only `_` that is authorized here or could it be `function f (a = arg1 => _) { }`? Do you know where I could find specifications on this?

**Comment by bucaran** [comment]
It could be anything, it's just the argument name. I updated the example. @pchaigno

**Comment by 50Wliu** [comment]
I looked into this a while ago and found that it was because the arrow regex matcher currently mandates an opening and closing parentheses before it'll match `=>`.  I couldn't get it to work properly without parentheses, but I can try again :).

**Comment by pchaigno** [comment]
Is this valid too?
```js
function f(a = x, y => x + y) {}
```

**Comment by bucaran** [comment]
yes

**Comment by pchaigno** [comment]
Ouch! That's going to be a tricky one...
