### ISSUE TITLE
template string bracket mismatch

### ISSUE THREAD

**Issue by schmittyjd** [atom/language-javascript#199]
Hey atom peeps. In the solarized dark repo we have a cool pull request that will be adding cool template string coloring for javascript <a href="https://github.com/atom/solarized-dark-syntax/pull/48">see here</a> and there was a bug uncovered showing that template strings do not match up closing brackets properly.

For ex:
![](https://cloud.githubusercontent.com/assets/337779/9291877/085efeae-439e-11e5-82a3-466ea8a3dd30.png)

in our case, the open bracket color is dark blue (which is correct) and the closing bracket is cyan, the closing bracket should be red and the bracket closing the function should be blue and not cyan. Would love to help out with this but I am a tad unfamiliar with how the language packages actually work. If anyone could help on this let me know! Thanks

**Comment by Victorystick** [comment]
Since the regexes used to mark the code with scopes can't have internal state (eg. a counter for the number of left brackets found), it can't know when it has found the right number of matching brackets.

If language-javascript was to use a JavaScript parser, like acorn, this and other similar issues could be fixed. But just using regexes, I don't think it can. At least not in the general case.

**Comment by cbankester** [comment]
@Victorystick Do you know of any plans to switch to a more fully-featured JS parser? This seems like a pretty big issue.

**Comment by 50Wliu** [comment]
@cbankester all Atom languages to my knowledge, and all 'official' ones, currently use a regex-based system.

**Comment by Victorystick** [comment]
I know of one Atom package, [TypeStrong/atom-typescript](https://github.com/TypeStrong/atom-typescript), that initially used a [code driven approach](https://github.com/TypeStrong/atom-typescript/blob/master/docs/grammar.md) to mark scopes, but it has since switched back to the regex grammars.

**Comment by 50Wliu** [comment]
For easy copy/paste into Atom for testing:
```js
`foo${function(){return the_stuff;}}`
`foo${() => {return the_stuff;}}`
```

My syntax theme is also highlighting this wrong, it might just be a JS issue and not bracket-matcher.  Will keep investigating.
![template-strings](https://cloud.githubusercontent.com/assets/2766036/9557972/696254fc-4dae-11e5-86f3-952634b6e6f6.png)

**Comment by schmittyjd** [comment]
any updates on this?

**Comment by 50Wliu** [comment]
I've been busy but I'll try to take a look at this this week.

**Comment by MethodGrab** [comment]
I don't know if this helps but language-babel

**Comment by MethodGrab** [comment]
I don't know if this helps but [language-babel](https://github.com/gandm/language-babel) highlights the brackets correctly so you might be able to use it's pattern:

![image](https://cloud.githubusercontent.com/assets/2421069/10933855/716989fe-82d3-11e5-8b70-0c985bb7147b.png)
