### ISSUE TITLE
setTimeout snippet tab stop function selection problem.

### ISSUE THREAD

**Issue by fiveisprime** [atom/language-javascript#22]
The setTimeout snippet (`timeout`) attempts to select the anonymous function as a tab stop, but the closing curly on the function body closes the selection.

```
setTimeout(${2:function () {\n\t$3\n}}, ${1:10});
```

It expands to this with the second tab stop selection acting like so (notice the selection does not include the `}`)

![screenshot 2014-03-29 11 20 19](https://cloud.githubusercontent.com/assets/1186948/2558690/a762d33a-b755-11e3-9c22-d7d1fce27191.png)

I tested escaping the curly brace (the way TextMate handles this), but that didn't seem to solve the problem.

**Comment by douggr** [comment]
Same here. This also applies to `interval`.

```
$ atom --version
0.165.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.7 (wheezy)
Release:        7.7
Codename:       wheezy
```

My solution was replace `timeout(${2:function () {\n\t$3\n}}, ${1:10});`
with `setTimeout($0, ${1:10});` and use the `f` or `fun` snippet together on `$0`.

IMHO, my version is even better than the original one.

**Comment by PierBover** [comment]
I'm having this same issue with a snippet I'm creating. Anyone found a solution to the closing curly bracket not being selected?

**Comment by traviskroberts** [comment]
Is this still a bug? I just tried the `\\` escape method and it worked for me.

my snippet: `allow(${1:object}).to receive(:${2:method})${3: \\{ ${4:value} \\}}`

**Comment by 50Wliu** [comment]
This (and `setInterval`) will be fixed in the next version of Atom.
