### ISSUE TITLE
Function call recognized as method definition

### ISSUE THREAD

**Issue by pchaigno** [atom/language-javascript#223]
This function call is recognized as a method definition:
```js
write("){");
```
It even [is in the tests](https://github.com/atom/language-javascript/blob/master/spec/javascript-spec.coffee#L518-L525) since f579460ff (the scopes shouldn't contain `meta.method.js`).
@50Wliu Is it a mistake or was it placed here as a bug to fix?

This is happening since #134 which added support for this kind of method definitions:
```js
var foo = {
  baz() {}
};
```

I'm working on a fix. ~~It will required to recognize JavaScript objects (`{}`) which requires to improve the current support for function and method definitions (to not mistake a function body for an object definition).~~ Actually, that won't fix it ~~and I found an other way :-)~~

EDIT: That probably should be a wontfix: I don't see how we can distinguish a function call from a method definition inside an object when there is `"){"` in argument.

**Comment by Victorystick** [comment]
I see what you mean. Yes, that seems pretty tough. I guess giving strings priority over method declarations doesn't work?

**Comment by pchaigno** [comment]
> I guess giving strings priority over method declarations doesn't work?

Nop, we don't know yet that there will be a string when we need to decide between function call and method definition :/

**Comment by 50Wliu** [comment]
Well, before it was being tokenized as
![](https://cloud.githubusercontent.com/assets/5256300/8888948/c6373810-32c3-11e5-8ddc-5c551992716a.png)
(taken from #175)

**Comment by pchaigno** [comment]
:smile: 
I guess it's a lot better now.

**Comment by Victorystick** [comment]
What about this? A helper function called constructor is called on a function, causing highlighting to break for function. Is this related?
```js
// breaks
window.Library = constructor(function Class(object) {
  ...
});

// works
window.Library = constructo(function Class(object) {
```
