### ISSUE TITLE
Split grammar from snippets

### ISSUE THREAD

**Issue by DaleJefferson** [atom/language-javascript#231]
I would like the javascript language grammar without the snippets, i'm not sure why they are bundled together.

```
language-javascript // installs both
language-javascript-grammar // installs grammar
language-javascript-snippets // installs snippets.
```

**Comment by 50Wliu** [comment]
This is currently how all languages are shipped.  Languages come with the following:
* Grammars
* List of supported filetypes
* Language-specific settings
* Snippets

The better solution by far would be an option to selectively disable snippets (and I see you've already commented on that issue).

Going to close this out unless you have another reason why you would like snippets to be separated from language packages.
