### ISSUE TITLE
export/import default as

### ISSUE THREAD

**Issue by Victorystick** [atom/language-javascript#232]
Anyone else find this strange?
```js
import { default as foo } from 'module';
export { default as foo } from 'module';
```
![screen shot 2015-10-02 at 15 42 24](https://cloud.githubusercontent.com/assets/703602/10248018/399392ec-691d-11e5-8e93-4febe53b3f25.png)

Why is `as` highlighted in the import statement, but `default` highlighted in the export?
In this situation, shouldn't `as` be highlighted in both, and `default` in neither? `default` is used as an identifier after all, not as a keyword.

**Comment by MaximSokolov** [comment]
`default` is [reserved word](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) It cannot be used as identifier

**Comment by Victorystick** [comment]
:tada: Gotta love the Atom Community! :tada:
