### ISSUE TITLE
Question about file type

### ISSUE THREAD

**Issue by matiasinsaurralde** [atom/language-javascript#247]
I'm developing [an Atom package](https://github.com/matiasinsaurralde/atom-scad-preview) for [OpenJSCAD](http://openjscad.org/).
Would it be possible to add .jscad as a supported file type (.jscad are basically JS files)?

**Comment by 50Wliu** [comment]
If it follows JS syntax exactly, then yes - just add it [here](https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L2) and then create a PR.

**Comment by matiasinsaurralde** [comment]
@50Wliu I just did it, thanks
