### ISSUE TITLE
RegExp highlighting in ternaries is broken

### ISSUE THREAD

**Issue by impinball** [atom/language-javascript#251]
This is a valid production, but the highlighter sees it as invalid:

```js
isAttr ? /["<&]/g : /[<&]/g
```

![broken highlighting example](http://s11.postimg.org/66ley4w6r/Screenshot_from_2015_11_08_01_44_00.png)

**Comment by impinball** [comment]
Wrapping the first regexp in parentheses fixes it:

![workaround image](http://s22.postimg.org/i2osaopep/Screenshot_from_2015_11_08_01_47_06.png)

**Comment by MaximSokolov** [comment]
It should be fixed in language-javascript v0.96.0

**Comment by 50Wliu** [comment]
Thanks @MaximSokolov.

@impinball This fix should already be in Atom 1.1.0, so please try updating to that.

**Comment by impinball** [comment]
Already did. :smile:
