### ISSUE TITLE
Fix not equal as one operator !== is not != and =

### ISSUE THREAD

**Issue by denis-sokolov** [atom/language-javascript#252]
_Please excuse if I incorrectly use some terminology._

Currently in my Atom `!==` is tokenized as `!=` and `=`, separately:
![1](https://cloud.githubusercontent.com/assets/113721/11023409/386ea0c4-8681-11e5-91f6-d7351835fdf0.png)

For a comparison, `===` is handled properly:
![2](https://cloud.githubusercontent.com/assets/113721/11023449/a074d440-8681-11e5-8bc5-13e3ae0b0a9c.png)

I came here because it breaks my ligature for it. See [a similar, resolved, issue for another language](https://github.com/JuliaLang/atom-language-julia/issues/49).

I tried looking in `javascript.cson`, but it seems to be the [operator is defined](https://github.com/atom/language-javascript/blob/0420acb07d4474cb02aa935d39eb1651d1d50b86/grammars/javascript.cson#L869) in a proper order there. Seems I do not understand something.

Thanks for your help!

**Comment by 50Wliu** [comment]
That's because this was fixed a few days ago and hence hasn't made it into a released version of Atom yet :smile:.  See #225.

**Comment by denis-sokolov** [comment]
Ah, thank you. Sorry for the duplicate.
