### ISSUE TITLE
Export statement containing "}" in string literal

### ISSUE THREAD

**Issue by ef4** [atom/language-javascript#253]
Highlighting is broken for this example:

```js
export default {
  bar: "}"
}
```

(I saw this bug in Github's syntax highlighting and I'm inferring that this is the relevant place to report the bug.)

**Comment by 50Wliu** [comment]
> I'm inferring that this is the relevant place to report the bug.)

Spot-on! :grinning:

However, it looks like this has already been fixed in the latest version, 0.100.0.  [Linguist](https://github.com/github/linguist) probably just has to update to it (it sounds like it'll be updated sometime next week) and then Github will highlight it properly as well.
