### ISSUE TITLE
Adding comments to JavaScript file causes Atom to hang.

### ISSUE THREAD

**Issue by cbarrick** [atom/language-javascript#26]
I'm on Atom **0.92.0** with Language Javascript **0.24.0**. The issue doesn't happen with this plugin disabled. No logs in the dev console or Console.app that I can find.

There is a thread on the forums: http://discuss.atom.io/t/bug-adding-comment-to-javascript-file-crashes-atom/6786
## Steps to reproduce:
1. Take the source below.
2. Put the cursor at the very beginning
3. Press <kbd>return</kbd>
4. Press <kbd>up</kbd>
5. Press <kbd>/</kbd>
## Expected:

A "/" character should be entered on a new line at the top of the document
## Actual:

Atom hangs.
## Sample source:

``` javascript
/// The parser's job is to read some source and extract the markdown. The hard part of the parsing
/// is handled by a packrat parser generated from `grammar/docparser.peg`. This module wraps the
/// parser to provide a higher-level interface.

var docparser = require('../grammar/docparser');


docparser.Parser.DocBlock = {
    isDocBlock: true,

    // Extracts the markdown from the node.
    getDocs: function () {
        var docs = '';
        this.elements.forEach(function (line) {
            docs += line.docs.textValue;
        })
        return docs;
    }
}


/// `parse(source)`
/// --------------------------------------------------
/// **TODO**: Summary
///
/// ### Arguments
/// 1. `source` *(String)*: The source code to parse.
///
/// ### Returns
/// *(Array of Strings)*: The blocks of markdown documentation in the source.

exports.parse = function (source) {
    var ast = docparser.parse(source);
    var docs = [];
    ast.elements.forEach(function (block) {
        if (block.isDocBlock) {
            docs.push(block.getDocs());
        }
    })
    return docs;
}
```

**Comment by baelter** [comment]
I'm experiencing this on 0.178.0

Toggling comments via editor:toggle-line-comments works fine but adding or removing comments manually hangs atom. Only in js files.

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by baelter** [comment]
Disabling autocomplete-plus option "Allow Backspace To Trigger Autocomplete" solves to problem. When that option is enabled the creator of suggestion list takes ~1min.

**Comment by baelter** [comment]
No I can not reproduce in --safe.
It is the compilation of suggestion list that hangs atom.

**Comment by baelter** [comment]
Sorry, not exclusive to javascript. Just observed the same bug in ruby.

**Comment by izuzak** [comment]
@baelter Sounds like a possible problem in autocomplete-plus (since you're not able to reproduce the problem in safe mode). Have you reported the issue over there as well? If so, can you add a link here for reference? Thanks.
