### ISSUE TITLE
Comment Behavior Less Flexible 

### ISSUE THREAD

**Issue by damassi** [atom/language-javascript#261]
With a recent release, comments are now automatically wrapped in multiline comments `/* */` rather than `//`. This leads to problems with commenting out code that already has comments within it, and in general just feels less flexible. 

There should be a solution for using multiline comments or inline (//) comments, but inline comments should be enabled by default (which was the previous behavior).

**Comment by 50Wliu** [comment]
> With a recent release, comments are now automatically wrapped in multiline comments /* */ rather than //. This leads to problems with commenting out code that already has comments within it, and in general just feels less flexible.

Hmm, I don't recall this being changed.  Odd.

**Comment by damassi** [comment]
Not sure, I just noticed this happening with Atom 1.1 or 1.2. And to be clearer, it happens when i have my cursor on a line, or I select a series of lines, and hit `cmd + /`

**Comment by damassi** [comment]
Actually, forgive me. This actually belongs in the language-javascript-jsx package.
