### ISSUE TITLE
No "Auto Close" option found in setting.

### ISSUE THREAD

**Issue by malpower** [atom/language-javascript#262]
Hey, i wanna turn off the "auto close" feature, but i couldn't find the option in setting page.
Any buddy can tell me how to turn it off?
I really don't like auto close......

Thank you~~~~~~~

**Comment by 50Wliu** [comment]
Can you elaborate on what you mean by "auto-close"?  Maybe through a gif or something?  Thanks.

**Comment by Victorystick** [comment]
@malpower Do you mean auto-closing of string quotes and brackets? `""`, `{}`...?

**Comment by malpower** [comment]
@Victorystick Yes, buddy, that's what i mean.
And any way to turn off this feature?

**Comment by lee-dohm** [comment]
@malpower, you can disable the [bracket-matcher package](https://github.com/atom/bracket-matcher) to turn it off globally. There is no method to turn it off language-by-language to my knowledge.

1. Open Settings View with <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms
1. Click the Packages tab
1. Search for the `bracket-matcher` package
1. Click the "Disable" button to disable it

Let us know if you have more questions.

**Comment by malpower** [comment]
OH~~~~~~~~~
@lee-dohm That's great, it works, no more auto closing.
Thank you so much.
You saved my life on atom.

**Comment by 50Wliu** [comment]
Glad you solved your issue @malpower!
