### ISSUE TITLE
Applying CSS styles to JavaScript syntax.

### ISSUE THREAD

**Issue by ugajin-nijagu** [atom/language-javascript#263]
This may be more a feature than a bug.

I first posted this issue on Nov.15., on the Atom Discuss forum. See: https://discuss.atom.io/t/issues-with-css-styles-on-javascript/22713. for details and screen-grabs. I then emailed support@github.com, who advise that I may report the matter here. However, the general topic appears to have been previously raised; see  issues 145, 137, 115, and 97, so I am doubtful that raising it again will be of much benefit.

I am including, a further screen-grab (in addition to those on the original post). This shows a detail from the same JavaScript file as shown in Atom Discuss grabs. However, here it is opened in Brackets. Note the variable names 'xmlns, e, and node' and the object properties named; 'id, cx, cy' and compare these with the earlier screenshots from the Atom UI. In Brackets the object property names 'id, cx, cy' are coloured light grey, whereas in Atom 'id' is coloured orange, and is styled with the CSS class; 'support.constant.dom.js'.

I like how Brackets colour codes syntax. It doesn't confuse property names, and variable names (other than the 'this' variable) are firstly coloured blue, and then purple when subsequently declared.  It may serve as a useful model to emulate.  Incidentally I am using Brackets here with the Atom Dark theme :)

I have looked at language-javascript-better, and language-javascript-semantic packages, and I don't think I like what language-javascript-better does to the sample code, and language-javascript-semantic does not appear to provide a solution.

I hope this is of interest. Thanks for considering matters.

-u

![screen shot 2015-11-23 at 11 24 34](https://cloud.githubusercontent.com/assets/13602549/11337099/38a62c80-91e2-11e5-981b-0fc60f20efc9.png)

**Comment by 50Wliu** [comment]
One great thing about Atom is that you can adjust the CSS styles yourself in the `styles.less` file, so if you don't like the orange coloring of `support.constant.dom.js`, you can easily disable that.  I would suggest however for you to try using the latest version of language-javascript (which you will have to install manually), as the latest release brings a lot of changes to property highlighting.

As for variables: there's a very large amount of effort required to properly highlight them (see https://github.com/atom/language-javascript/issues/196#issuecomment-130266077 for an example).  It's definitely on the roadmap though.

Does that help?

/cc @Victorystick @MaximSokolov for any other comments
/cc @bucaran because I know you're always interested in these conversations :)

**Comment by Victorystick** [comment]
From what I understand Brackets uses CodeMirror, which has this feature enabled by default for its languages. See [Rollupjs.org](http://rollupjs.org/) for another usage example. I'm unfamiliar with what CodeMirror actually does to highlight code.

**Comment by u-gajin** [comment]
I tried v0.102.0 - it is shockingly awful (unless you like reading red text) - quite similar in effect to the language-javascript-better package. I've had to uninstall pronto :)

I don't dislike the orange colouring - what I dislike is the confusion, where this class is incorrectly applied.
How do I disable `support.constant.dom.js` - I am assuming this is not the same as overwriting, or is it?

Many thanks.
-u

**Comment by MaximSokolov** [comment]
> I tried v0.102.0 - it is shockingly awful (unless you like reading red text) - quite similar in effect to the language-javascript-better package. I've had to uninstall pronto :)

What syntax theme are you using? Is it One Dark Syntax?

> How do I disable support.constant.dom.js - I am assuming this is not the same as overwriting, or is it?

Add this to stylesheet:
```less
atom-text-editor::shadow {
  .support.constant.dom.js {
    color: @color;
  }
}
```

**Comment by Victorystick** [comment]
CodeMirror appears to use a [specialised javascript tokeniser](https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js) for it's highlighting. It's not regex based.

**Comment by u-gajin** [comment]
Many thanks - I guess that counts as disabling, as opposed to overwriting the matching hue.
There is another syntax issue (see screen grab below):
 
'this.obj' has the identifier `support.class.js` - I am unable to separate `this`, `.` (period), or `obj`, although  the `.` (period) after `obj` has the identifier of `meta.class.js`.
Similarly, `this.El`, which has a single identifier of `entity.name.type.instance.js`..

I would like to be able to access separate identifiers.
All thoughts/comments welcome.

Thanks again all.

![screen shot 2015-11-23 at 16 25 17](https://cloud.githubusercontent.com/assets/13602549/11342396/1fa19856-91ff-11e5-9027-8af39ff3c93e.png)

**Comment by 50Wliu** [comment]
^ I think I just merged the PR that fixed that :smile:.

**Comment by MaximSokolov** [comment]
Only `this` in `this.obj.prototype`

**Comment by 50Wliu** [comment]
@u-gajin: Just published v0.102.1, could you try that out?  You might still see swatches of red, but unfortunately that's just how One Dark decided to style things (cc @simurai again).

**Comment by u-gajin** [comment]
Can do. 
I now have `this` as variable.language.js, `.obj` as `support.class.js`, and as you say swatches of red :)

-u

**Comment by simurai** [comment]
> You might still see swatches of `red`, but unfortunately that's just how One Dark decided to style things

One Dark is originally based on base16-tomorrow which uses red for variables. But I agree, using red for highlighting might make it look like it's some kind of "error". I'll make a new issue in the theme's repo to reconsider it.

**Comment by u-gajin** [comment]
@50Wliu Can I ask what is 'PR' and what did you 'merge'?
I have overwritten `.variable.other.property.js, `.variable.other.object.js`, and `.entity.name.function.js` to emulate v0.98.0 - much happier :)

**Comment by lee-dohm** [comment]
@u-gajin GitHub Help has [a great introductory article on Pull Requests (PRs)](https://help.github.com/articles/using-pull-requests/). Pull Requests are a way of submitting a change or set of changes to a repository for review and eventual "merging" into the repository.

**Comment by 50Wliu** [comment]
Assuming fixed, so closing.  Feel free to comment here if it's still an issue.
