### ISSUE TITLE
Commented lines/blocks not properly highlighted in import statement.

### ISSUE THREAD

**Issue by armed** [atom/language-javascript#267]
Hi!

Atom version: 1.2.4
language-javascript version: 0.98.0
OS: Mac OS X 10.11

Here is screenshots:
<img width="234" alt="screen shot 2015-11-26 at 1 29 42 pm" src="https://cloud.githubusercontent.com/assets/223060/11417537/23c2e95e-9442-11e5-87eb-c29f022f8489.png">
<img width="214" alt="screen shot 2015-11-26 at 1 32 46 pm" src="https://cloud.githubusercontent.com/assets/223060/11417556/407c1980-9442-11e5-9966-2a4b6432db20.png">
<img width="695" alt="screen shot 2015-11-26 at 1 36 33 pm" src="https://cloud.githubusercontent.com/assets/223060/11417630/c2ebdefa-9442-11e5-8086-2c04d23d7e1b.png">

**Comment by 50Wliu** [comment]
Confirmed.  Working on a fix right now.

**Comment by MaximSokolov** [comment]
I alredy fixed locally

**Comment by 50Wliu** [comment]
Oh, ok!

**Comment by MaximSokolov** [comment]
Forgot about `Fixes #267` in #269
