### ISSUE TITLE
$exports isn't highlighted correctly

### ISSUE THREAD

**Issue by Victorystick** [atom/language-javascript#268]
An extract from [zloirock/core-js](https://github.com/zloirock/core-js) that breaks highlighting.

![screen shot 2015-11-26 at 11 29 07](https://cloud.githubusercontent.com/assets/703602/11420829/068602c4-9431-11e5-9235-a883314596f2.png)

```js
}
$export($export.S + $export.F * !DESCRIPTORS, 'Object', {
  // 19.1.2.6 / 15.2.3.3 Object.getOwnPropertyDescriptor(O, P)
  getOwnPropertyDescriptor: $.getDesc,
  // 19.1.2.4 / 15.2.3.6 Object.defineProperty(O, P, Attributes)
  defineProperty: $.setDesc,
  // 19.1.2.3 / 15.2.3.7 Object.defineProperties(O, Properties)
  defineProperties: defineProperties
});

  // IE 8- don't enum bug keys
var keys1 = ('constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,' +
            'toLocaleString,toString,valueOf').split(',')
  // Additional keys for getOwnPropertyNames
  , keys2 = keys1.concat('length', 'prototype')
```

**Comment by 50Wliu** [comment]
I think there's two issues here:
1. `$export` is being broken up into two tokens and we're only catching the latter `export`.
2. Comments aren't supported within `import`/`export` blocks yet (see #267, with a fix in #269).

**Comment by MaximSokolov** [comment]
It's not supposed to be a `import`/`export` block. Not sure why `export` in `$export` is catched by `\\b(export)\\b`

**Comment by 50Wliu** [comment]
Because $ isn't a word-character, I suppose.

(And yeah, I know that it isn't supposed to be an export block.  Sorry if I wasn't clear on that)
