### ISSUE TITLE
delete key word is not recognized

### ISSUE THREAD

**Issue by boyangwang** [atom/language-javascript#273]
See below screenshot

![delete](https://cloud.githubusercontent.com/assets/2408273/11495648/de3877a0-9847-11e5-8af5-34838ffc8a2a.png)

**Comment by Victorystick** [comment]
This is due to atom/one-dark-syntax not highlighting those keywords. It _does work_:

```js
var a = {};
a.foo = 'bar';
delete a.foo;
```

**Comment by boyangwang** [comment]
Hi, thanks for the prompt reply. So you are saying the theme is giving it
the same color as normal identifiers? Why would it treat this keyword
specially?

**Comment by Victorystick** [comment]
Apparently [operator keywords](https://github.com/atom/one-dark-syntax/blob/master/styles/language.less#L27) are highlighted the same as plain text. That's just the way the theme is designed.

**Comment by boyangwang** [comment]
Thanks. Guess we can close it now.

**Comment by 50Wliu** [comment]
@boyangwang Feel free to open an issue on the one-dark-syntax repo if you want to.

**Comment by Victorystick** [comment]
@50Wliu Same as #274.
