### ISSUE TITLE
foreach loop, "in" is not highlighted as keyword

### ISSUE THREAD

**Issue by boyangwang** [atom/language-javascript#274]
See screenshot

![screenshot_2015-12-01_16-26-47](https://cloud.githubusercontent.com/assets/2408273/11495717/5c2f735c-9848-11e5-8eb1-2a25716584d4.png)

**Comment by Victorystick** [comment]
This is due to atom/one-dark-syntax not highlighting those keywords. It _does work_:

```js
function destoryCompleted() {
  for (var id in _todos) {
```

**Comment by 50Wliu** [comment]
THanks @Victorystick.

/cc @simurai
