### ISSUE TITLE
Syntax highlighting broken on long lines

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-javascript#275]
See the following example:

![ss](https://www.dropbox.com/s/z2lu2ojco73d1gw/Screenshot%202015-12-02%2015.21.09.png?dl=1)

Somewhere after 150 characters or so, syntax highlighting gives up and makes the rest of the line white.

**Comment by 50Wliu** [comment]
This is a limitation in Atom put in place to prevent performance issues while highlighting long lines.  Please see atom/atom#1667 for more details.

**Comment by adambuczynski** [comment]
Thanks
