### ISSUE TITLE
Request: javascript for `object[property]`

### ISSUE THREAD

**Issue by KSXGitHub** [atom/language-javascript#288]
`propertyname` in `object.propertyname` and `(expression).propertyname` is considered as a property and so does `propertyvar` in `object[propertyvar]` and `(expression)[propertyvar]`?

**Comment by Victorystick** [comment]
`propertyvar` is a variable and not a property name, so I don't think it should have the same scopes.

**Comment by 50Wliu** [comment]
Agreed.
