### ISSUE TITLE
Missing commas are not inserted

### ISSUE THREAD

**Issue by willnwhite** [atom/language-javascript#299]
```
{ key: value 
  key: value } => { key: value, 
                    key: value }
```

**Comment by 50Wliu** [comment]
@willnwhite Can you provide some more information?  Are you using the `kv` snippet?

**Comment by willnwhite** [comment]
Hi! No, I hadn't been using the `kv` snippet, but I will be from now. It looks like all that does is insert a `: ` though.

**Comment by 50Wliu** [comment]
Hmm ok, then did you expect this package to automagically insert a `,` after each kv pair?  If so, you might want to look for another package: `language-javascript` only highlights and provides snippets.

**Comment by willnwhite** [comment]
Okay, will do.
