### ISSUE TITLE
Improper method-call scope applied

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-javascript#304]
For the following code:

![ss](https://www.dropbox.com/s/qcpr6qzwdsetzpe/Screenshot%202016-01-18%2015.07.53.png?dl=1)

The property `client` gets incorrectly marked as `meta.method-call.js`, the property `benefits` is just `source.js`
When I switch them around, both become `meta.method-call.js`:

![ss](https://www.dropbox.com/s/g70ad1nnyzxoogx/Screenshot%202016-01-18%2015.06.46.png?dl=1)

Seems to me they both should just be `source.js` or something like `meta.property.js` if that exists. Definitely shouldn't matter in what order they are placed.

A lot of buggy behaviour like this since the latest update to langauge-javascript, but I'm glad we're getting some more fine grained scoping.

**Comment by 50Wliu** [comment]
Thanks for the report :)

**Comment by adambuczynski** [comment]
A couple more inconsistencies related to properties being marked as method calls:

![ss](https://www.dropbox.com/s/aw9tsfevt2syyqq/Screenshot%202016-01-18%2015.43.16.png?dl=1)

**Comment by MaximSokolov** [comment]
Arguments are part of function call:
```
functionCall(...)
|          |^   ^  - punctuation.definition.arguments.begin/end
^----------^    |  - entity.name.function
^---------------^  - meta.function-call
```
`meta.function-call` is not supposed to be highlighted, it provides context:
```less
.function-call, .method-call {
  & > .entity.name {...}

  & > .punctuation.definition {...}

  // is not tagged so far
  // .variable.argument {...}
}

.function {
  & > .entity.name {...}

  & > .punctuation.definition {...}

  .variable.parameter {...}
}
```
> Seems to me they both should just be `source.js` or something like `meta.property.js` if that exists.
 
Object keys don't have an own scope. Refs #287, #137

> A lot of buggy behaviour like this since the latest update to langauge-javascript

Please create a new issue if you find bugs. Thanks!

_Support for function/method calls added in #242_

**Comment by adambuczynski** [comment]
Thanks for the clarification @MaximSokolov, I will check my syntax stylesheet and remove highlighting of meta elements.
