### ISSUE TITLE
Support class not consistent

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-javascript#309]
Support classes are not being marked consistently:

![ss](https://www.dropbox.com/s/xuudw3voectscdd/Screenshot%202016-01-20%2008.25.40.png?dl=1)

`Ember` is first being marked as a `support.class`, while later it's marked as a plain `variable.other.object`.

**Comment by jonathandelgado** [comment]
This is also the case for `support.variable`, `process` on it's own is referenced as `support.variable`, but once you specify `process.attribute`, it will cause the same result as @adambuczynski describes, it is now `variable.other.object`.
