### ISSUE TITLE
Add multi-caret support to all snippets

### ISSUE THREAD

**Issue by backspaces** [atom/language-javascript#31]
The final result of https://github.com/atom/snippets/issues/11 allows a snippet to have duplicate names, very useful for most snippets that use the same name in multiple places.

For example:

    "for": {
      "prefix": "for",
      "body": "for (var i = 0; i < ${1:array}.length; i++) {\n\t${2:array}[i]\n}"
    },

can now be converted to:

    "for": {
      "prefix": "for",
      "body": "for (var i = 0; i < ${1:array}.length; i++) {\n\t${1:array}[i]\n}"
    },

I tried this by adding 

    {
      ".source.js": {
        "xxx": {
          "prefix": "xxx",
          "body": "for (var i = 0; i < ${1:array}.length; i++) {\n\t${1:array}[i]\n}"
        },
      },
    }

to my snippets and it works just fine and looks sexy!

**Comment by 50Wliu** [comment]
This should already be implemented - I just checked through all the snippets and the applicable ones have multi-caret support.
