### ISSUE TITLE
Highlighting broken when regex contains speech marks

### ISSUE THREAD

**Issue by WickyNilliams** [atom/language-javascript#315]
I first noticed this problem on github.com itself, but have noticed it also affects the atom highlighting (I believe the same scheme is used? At least that is what github support told me).

Here is the offending code, which you can see is broken here on the site itself!

```js
const isCssImage = val => /^url\(["']?http/.test(val);

function something() {
  console.log("WTF, highlighting completely screwed");
}
```

And here is a screenshot of it broken in Atom:

![screen shot 2016-01-28 at 22 55 19](https://cloud.githubusercontent.com/assets/1091390/12669125/a4921148-c612-11e5-987f-cfcdcb4042fa.png)

**Comment by 50Wliu** [comment]
Thanks for the report :)
Yes, the same grammar is used for both github.com and Atom.
