### ISSUE TITLE
Many scopes are not included for them authors

### ISSUE THREAD

**Issue by smlombardi** [atom/language-javascript#317]
A great many entities that are defined in a highlighting package such as PrismJS are not present in this language package.

For example, here's a line highlighted on a web page with Prism.js
![screen shot 2016-01-30 at 6 05 51 pm](https://cloud.githubusercontent.com/assets/835148/12699066/38365e4e-c77c-11e5-9fbd-11516588a334.png)

See that magenta `.map` and `.clone`?  I assume those are methods.  In this package, they are scoped `source.js` like all non-defined strings.  Is it possible to recognize methods are put a scope so we can theme it?

**Comment by 50Wliu** [comment]
@smlombardi Are you sure?  There should be support for methods and properties now - lots of people were actually complaining about it ("too colorful") in the last Atom release.

**Comment by 50Wliu** [comment]
No response, closing.  Feel free to comment here if it's still an issue.
