### ISSUE TITLE
Inconsistent scoping of decimals

### ISSUE THREAD

**Issue by chbk** [atom/language-javascript#318]
I noticed some bugs on decimal numbers:

![c](https://cloud.githubusercontent.com/assets/7478535/12719149/aed8a43a-c8f3-11e5-8764-76b07e80e982.png)

```javascript
0.9 == .9

9.0 == 9.
```

![a](https://cloud.githubusercontent.com/assets/7478535/12719147/a5749822-c8f3-11e5-83ff-3a2c1d9f4b5a.png)

![b](https://cloud.githubusercontent.com/assets/7478535/12719148/ab71d5dc-c8f3-11e5-8d3a-27ccd0b095b6.png)

On the first line, `.9` shouldn't be illegal: [Floating-point literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Floating-point_literals).

Also, periods in numbers should have their own scope IMO, different from `constant.numeric`, the same way plus and minus signs are `keyword.operator`.

**Comment by 50Wliu** [comment]
Yeah periods in numbers definitely shouldn't be listed as properties.
