### ISSUE TITLE
Mark `CONSTANT` properties as constants

### ISSUE THREAD

**Issue by adambuczynski** [atom/language-javascript#326]
For example, when I have a constant which is an object, it becomes a regular `variable.other.object.js` and loses the constant scope `constant.other.js` and corresponding coloring:

![image](https://cloud.githubusercontent.com/assets/490562/13278524/fbf7c1c0-db35-11e5-934e-a86470aa8faf.png)

**Comment by 50Wliu** [comment]
@adambuczynski I can no longer reproduce this using language-javascript  0.113.0, so I'm going to assume that it's been fixed in one of the newer versions than Atom is currently running on.

**Comment by adambuczynski** [comment]
Yes @50Wliu , seems to be working correctly now :+1:
