### ISSUE TITLE
Incorrect css for JS contant objects or functions

### ISSUE THREAD

**Issue by Nokel81** [atom/language-javascript#337]
I have noticed that if a constant has sub items (in JS) that if you call of use them like
const data = { "name":"Test" }; console.log(data.name); console.log(data);

And look at the calling data (the one in the console log) in the developer tools then it has class "span.variable.other.object.js" but the declaration has "span.constant.other.js", the log of just the data also is "span.constant.other.js"

I believe that this is an error

**Comment by 50Wliu** [comment]
This is a limitation of regex parsing.  We can only identify constants when they are defined or `ALL_UPPERCASE`.

Please tell me if I'm misunderstanding something.

**Comment by Nokel81** [comment]
Ok, bad example. My actual example is this (same behavior)
`const DATA ={ "name":"Test" };`
`console.log(DATA.name);`
`console.log(data);`

**Comment by 50Wliu** [comment]
@Nokel81 Thanks for the update!  I can't reproduce this using language-javascript 0.113.0, so I'm going to assume that it's been fixed in one of the newer versions than Atom is currently running on.
