### ISSUE TITLE
Autocompletion breaking at accent

### ISSUE THREAD

**Issue by Bouzmine** [atom/language-javascript#340]
When I type in JavaScript there is always autocompletion for word that are not functions or variables. These are useful but as I am a French speaker, I frequently use accents in strings. What happens is the word is cut just before the letter with the accent (e.g. numéro -> num).

**Comment by lee-dohm** [comment]
From your description, this has nothing to do with the language-javascript package. Would you mind reopening it on the [autocomplete-plus package](https://github.com/atom/autocomplete-plus)?
