### ISSUE TITLE
Arrow functions that have one parameter and no parentheses are not recognized as functions

### ISSUE THREAD

**Issue by not-an-aardvark** [atom/language-javascript#342]
When an arrow function has only one parameter, parentheses around that parameter are optional. However, atom does not recognize the function properly if the parentheses are omitted.

Example code:

```js
var multiplyByTwo = (value) => {
  return value * 2;
};

var multiplybyThree = value => {
  return value * 3;
};

```

[Screenshot of that code in atom -- note that the second function is not blue](https://i.gyazo.com/83407394b4af5368af5c7843aea1f12c.png)

I'm using Atom 1.6.0 on OSX.

**Comment by 50Wliu** [comment]
This was fixed by #312 but is not in an Atom release yet.
