### ISSUE TITLE
The comment block trigger is not working.

### ISSUE THREAD

**Issue by Redsandro** [atom/language-javascript#353]
There is a trigger for `/**` but it's not working. The rest works fine.

---

Shameless noob question: How do I add/edit/rename snippets?

**Comment by 50Wliu** [comment]
@Redsandro When you type `/**`, then press tab, does the snippet work?

You can add snippets in your personal `snippets.cson` file - you can open it from the `Atom` menu on Mac, `File` on Windows, and `Edit` on Linux.

**Comment by Redsandro** [comment]
@50Wliu ok I feel a bit silly now. It works indeed. I never used tab, I always press enter. It works for the other snippets but not for the comment snippet. Not a problem. I can press tab. :smile: 

And thanks for letting me know where to edit the snippets.

**Comment by 50Wliu** [comment]
Yeah, that's an unfortunate side-effect of autocomplete-snippets depending on autocomplete-plus, which only shows autocompletions if they start with a letter :P.
