### ISSUE TITLE
Syntax highlighting JavaScript not working when using block comments in a string

### ISSUE THREAD

**Issue by doberkofler** [atom/language-javascript#359]
### Description

The syntax highlighting of JavaScript does seem to have a problem when using block comments in a string as reproducible in the following simple example:

```javascript
/*
const files = glob.sync('src/**/*.+(gif|png|jpg|ico)');
*/
```

### Versions

1.7.0

**Comment by MaximSokolov** [comment]
Strings don't have to be tokenized inside comments, so this code is actually invalid. Chrome console:
![image](https://cloud.githubusercontent.com/assets/2943616/14542706/f9c54334-0298-11e6-9083-ec2111a02f9a.png)

**Comment by 50Wliu** [comment]
Thanks for the example @MaximSokolov.
