### ISSUE TITLE
Everything after valid regular expression highlighted as error

### ISSUE THREAD

**Issue by signate** [atom/language-javascript#366]
To reproduce copy & paste `/{"}/` regexp into any javascript file.

<img width="162" alt="screen shot 2016-04-17 at 23 57 44" src="https://cloud.githubusercontent.com/assets/4222734/14589995/38f8d1f4-04f8-11e6-9ad0-56e410382fc7.png">

**Comment by creeperyang** [comment]
Same issue.

<img width="534" alt="2016-05-23 1 37 27" src="https://cloud.githubusercontent.com/assets/8046480/15461209/908c9c98-20eb-11e6-9fd0-71e08a75730a.png">
