### ISSUE TITLE
Function Parameters on Multiple Lines in ES6/Class Format

### ISSUE THREAD

**Issue by jonathandelgado** [atom/language-javascript#376]
There is an issue with parameters spanning multiple lines when it comes to the ES6 object/class function definitions. Additionally, it appears to not affect constructors since they have a custom capture. I attached a screenshot to better illustrate the issue.

I did some digging in the source in an attempt to create a PR; I rapidly came to the conclusion the capturing was a little over my head. I did notice, however, the `function_params` seems to be the offending capture in this issue, versus `function_innards` being called where the arguments work as intended.

For some additional notes, the instances of this problem are marked as `meta.arguments.js`, which makes me assume they are being interpreted as a function call, versus a declaration.

Also, a side note, all of these examples work if the parameters were on one line.

![params](https://cloud.githubusercontent.com/assets/1841149/15554346/91b0a5ea-2278-11e6-9694-71b793253f22.png)

**Comment by 50Wliu** [comment]
See also #361.
