### ISSUE TITLE
atom hangs when opening up a specific javascript file.

### ISSUE THREAD

**Issue by rbeathar** [atom/language-javascript#379]
I have the latest version (1.8) of atom. If I open up the json-refs-standalone.js javascript file from the json-refs from https://github.com/whitlockjc/json-refs/tree/master/docs site.
      https://raw.githubusercontent.com/whitlockjc/json-refs/master/browser/json-refs-standalone.js
Atom will hang.  I have run atom in safe mode and removed all files in my .atom directory and atom still hangs on opening that file.

I have narrowed it down to language-javascript package by removing all packages in my .atom directory and disabling just language-javascript package before opening up the file. The file opens without any of the highlighting niceties. If I re-enable language-javascript,  atom will then hang on opening up the file.

Subsequently I have downloaded the community package called language-better-javascript and it seem to be able to handle this file without hanging atom.io. 

Versions
=======
language-javascript: 0.110.0

atom --version
   Atom    : 1.8.0
   Electron: 0.36.8
   Chrome  : 47.0.2526.110
   Node    : 5.1.1

apm --version
    apm  1.9.2
    npm  2.13.3
    node 0.10.40
    python 2.7.10
    git 2.7.4

MacOS: ElCapitan

**Comment by MaximSokolov** [comment]
Duplicate of atom/atom#979

**Comment by 50Wliu** [comment]
Just to make sure before closing this as a duplicate: if the last line is removed does the performance problem still occur?

**Comment by rbeathar** [comment]
If I remove the last line in that file there is no issue. I would agree that this is a duplicate of Issue 979. 

I originally saw 979 but dismissed it because I did not look at the file closely. I did not realize that the last line was that large.
