### ISSUE TITLE
Highlighting accepts missing function keyword for methods in object literal

### ISSUE THREAD

**Issue by kriscooke** [atom/language-javascript#382]
I have had issues with this (very common for me) syntax error and am trying to catch it directly when I am making the error. In Sublime, the below syntax will not be highlighted just as any other method (as you can see it is in Atom below). 

Any hints/info/advice?

Atom:
<img width="294" alt="screen shot 2016-06-22 at 9 50 18 am" src="https://cloud.githubusercontent.com/assets/5522075/16275451/dcf6436a-385e-11e6-97d6-0b6974549721.png">
Sublime:
<img width="280" alt="screen shot 2016-06-22 at 9 55 51 am" src="https://cloud.githubusercontent.com/assets/5522075/16275598/8aabccbe-385f-11e6-93c0-0479800a9dd6.png">

**Comment by 50Wliu** [comment]
I would suggest using a linter.  However, if Sublime is catching this using syntax highlighting, then I believe Atom can too (as long as Sublime is also using regexes).

**Comment by gandm** [comment]
That's valid es2015 syntax. Shorthand method names in object literal syntax.

**Comment by 50Wliu** [comment]
Bleh.  You're totally correct @gandm.  Should have looked at the object declaration closer.

**Comment by kriscooke** [comment]
Hm, I had a funny feeling about that. Thanks - I'll have a look at setting my linter to catch es2015 :( 
[Or ideally, upgrade my build tool that's barfing on it].
