### ISSUE TITLE
function declaration brace classes

### ISSUE THREAD

**Issue by PlaidPhantom** [atom/language-javascript#388]
There seems to be an inconsistency in how empty blocks are parsed:

![javascript](https://cloud.githubusercontent.com/assets/678150/17284434/3350261e-5780-11e6-9afa-bbcdabd692e8.png)

**Comment by 50Wliu** [comment]
Actually, I can't reproduce this using language-javascript@0.119.0, so I'm going to assume that this has been fixed in 1.9.0-beta0 and above.
