### ISSUE TITLE
ES6 classes `constructor` autocomplete and highlighting 

### ISSUE THREAD

**Issue by ZakariaRidouh** [atom/language-javascript#389]
Currently, it doesn't auto complete nor does it highlight it specially. It would be a pretty nice addition.

Cheers!

**Comment by 50Wliu** [comment]
What Atom version are you on?  It's highlighting fine for me.

**Comment by ZakariaRidouh** [comment]
I'm on version 1.9.0.


Cheers.






On Tue, Aug 2, 2016 at 7:44 AM -0700, "Wliu" <notifications@github.com> wrote:





What Atom version are you on?  It's highlighting fine for me.

---

**Comment by 50Wliu** [comment]
Ok, and can you provide a screenshot of the highlighting as well as what you would expect instead?

**Comment by 50Wliu** [comment]
No response, closing.  Feel free to comment here if it's still an issue.
