### ISSUE TITLE
Wrong highlighting for optional parameters in jsdoc comments

### ISSUE THREAD

**Issue by rpadovani** [atom/language-javascript#390]
[Optional params](http://usejsdoc.org/tags-param.html) of jsdoc aren't highlighted.

![screenshot from 2016-08-03 09-53-43](https://cloud.githubusercontent.com/assets/1713343/17358089/502952a6-5960-11e6-9ee5-db5f3bdbf046.png)

**Comment by gurbraj** [comment]
hmm this issue seems to have come back up

Using latest atom 1.58
