### ISSUE TITLE
wrong highlighting for words that starts with "constructor"

### ISSUE THREAD

**Issue by peonmodel** [atom/language-javascript#391]
currently at version 1.9.1

if a key starts with "constructor", only "constructor" will be highlighted as different color, also screw up highlighting for other keys in the object

Using the Base16 Tomorrow Dark theme (bug is independent of theme)
```js
a = {
  constructorExtension: {  // result will be <blue>constructor</blue>Extension
    keys: {},  // keys will be white
    'morekeys': {},  // 'morekeys' will be white when it is usually green
    someFn: function(){},  // someFn is usually blue, but is now white
    'otherFn': function(){},  // the quotes are supposed to be green and otherFn blue, but is all white
  },
};
```
compare against
```js
b = {
  construXXXXctorExtension: {  // bug do not occur if construXXXXctor
    keys: {},  
    'morekeys': {},  
    someFn: function(){},  
    'otherFn': function(){}, 
  },
};
```

**Comment by 50Wliu** [comment]
Thanks for the report @peonmodel!

In the future if you want to automatically syntax highlight code blocks on GitHub, simply add the language next to the three backticks like so:
```js

**Comment by NatalieWolfe** [comment]
Relatedly, this also messes up object literals.

```js
var foo = {
  constructor: 'Foo',
  bar: 'fizz'
}
```

Vs
```js
var foo = {
  construXXXXctor: 'Foo',
  bar: 'fizz'
}
```

**Comment by 50Wliu** [comment]
@NatalieWolfe That's a different bug: #334
