### ISSUE TITLE
JSDoc highlighting with multiple spaces

### ISSUE THREAD

**Issue by 22sk** [atom/language-javascript#400]
In JavaScript, parameter types and names are highlighted. That does not work if there is more than one space after the type, like in this example:

```javascript
/**
 * Does cool things
 *
 * @param {number}            foo First parameter
 * @param {SomeLongClassName} bar Second parameter
 */
```

`{SomeLongClassName}` as well as `bar` are highlighted, while `{number}` and `foo` aren't.
That issue does also appear on GitHub, as seen above.

**Comment by 50Wliu** [comment]
This was fixed just 3 days go :).  GitHub should pick up the fix when they feel like it, and it should be fixed in Atom starting in Atom 1.11.0.
