### ISSUE TITLE
Wrong highlighting for constants with dollar sign

### ISSUE THREAD

**Issue by MaximSokolov** [atom/language-javascript#409]
```js
CON$TANT
ABC$
```

**Comment by Alhadis** [comment]
Will fix once #407 and #408 get merged. :)

**Comment by MaximSokolov** [comment]
Could you also fix #413 as well?

**Comment by Alhadis** [comment]
I was in the middle of commenting on #413 when you asked, haha.

I was about to say I saw this, but decided to leave it because I wasn't sure. I think it makes sense to fix it. =)

BTW, constants that start with underscores aren't matched either. I fixed that too.
