### ISSUE TITLE
Feature: Snippets support  for .ts

### ISSUE THREAD

**Issue by FabioAntunes** [atom/language-javascript#416]
It would be nice if this package could support `.ts` files, I'm so used to the snippets that I miss them when working with .ts files.

**Comment by Alhadis** [comment]
What's wrong with installing [atom-typescript](https://atom.io/packages/atom-typescript) or [language-typescript-grammars-only](https://atom.io/packages/language-typescript-grammars-only)...?

**Comment by FabioAntunes** [comment]
The snippets ...?

**Comment by Alhadis** [comment]
I'm not sure I understand what the issue is. Do you mean using snippets that you've scoped to `source.ts` inside a JavaScript file? Or... what?

**Comment by FabioAntunes** [comment]
Using the snippets available on this package, on .ts files. Like doing `log` press tab and get a `console.log()` and so on

**Comment by Alhadis** [comment]
Easy to fix: just copy your favourites to your user-snippets file.
