### ISSUE TITLE
Display incorrect color for any decimal number < 0 in Ruby file

### ISSUE THREAD

**Issue by haharicky** [atom/language-javascript#442]
Display incorrect color for any decimal number < 0 in Ruby file
**Reproduction Steps:**

1. create new ruby file (test.rb)
2. type any decimal number which < 0 (i.e 0.1)
3. "0." will show in white and "1" will show in orange

**Expected behavior:**

Expect whole number in same color

**Screenshots and GIFs**

![Screenshots](http://i.giphy.com/kegcUfHthgbYs.gif)

**Atom version:** 1.11.1
**OS and version:** MacOSX 10.10.2 

**Installed packages:**

api-blueprint-preview@0.7.0
atom-ternjs@0.14.2
auto-indent@0.5.0
autocomplete-modules@1.5.2
autocomplete-python@1.8.4
autocomplete-ruby@0.1.0
file-icons@1.7.21
language-api-blueprint@1.0.2
last-cursor-position@0.9.0
linter@1.11.14
linter-api-blueprint@0.4.0
merge-conflicts@1.4.4
minimap@4.24.7
minimap-bookmarks@0.4.1
minimap-git-diff@4.3.1
ruby-block@0.3.5
ruby-test@0.9.17
trailing-spaces@0.3.2

**Additional information:**

* Problem can be reproduced in safe mode: [Yes]
* Problem started happening recently, didn't happen in an older version of Atom: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by Alhadis** [comment]
Think you're in the wrong repository. This is JavaScript.

**Comment by Alhadis** [comment]
See what CoffeeScript does to people?
