### ISSUE TITLE
CSS highlighting in tagged template strings stopped working

### ISSUE THREAD

**Issue by felipeccastro** [atom/language-javascript#448]
I'm experimenting on doing single file components with html, css and javascript, and it's really handy to have the proper syntax highlighting for each tagged template.

This used to work until recently, but since the last Atom update, the css syntax highlighting (html still does) stopped working:

<img width="445" alt="screen shot 2016-10-21 at 9 35 36 am" src="https://cloud.githubusercontent.com/assets/3835098/19597234/20596e8a-9772-11e6-8e57-db51240fd205.png">

Here is the PR where this feature was introduced: https://github.com/atom/language-javascript/pull/282

**Comment by MaximSokolov** [comment]
This feature has been reverted. See #338 #341 for details
