### ISSUE TITLE
`import` can be used as a method name, and this confuses the grammar.

### ISSUE THREAD

**Issue by danfuzz** [atom/language-javascript#452]
Version: 0.119.0

If `import` is used as a method name, the grammar gets confused. For example, take this file:

```javascript
class Blort {
  normal(x) {
    if (x > 10) {
      error(`${x} is too big!`);
    }    
  }

  import(x) {
    if (x > 10) {
      error(`${x} is too big!`);
    }
  }
}
```

Here's how it gets rendered for me:

![rendered](https://cloud.githubusercontent.com/assets/1090235/19777462/27ae889a-9c2d-11e6-89a8-a2a1ccd526c0.png)

You can see that the first method gets proper markup but the second doesn't. In this case, it seems to miss that first backtick as an open-quote-ish thing, so the rest of the file after the second backtick is taken to be an unterminated string.

**Comment by 50Wliu** [comment]
Thanks for reporting!

**Comment by danfuzz** [comment]
Hi! I did a bit of research, and I believe that the culprit is <https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L466-468>, reproduced here:

```
   # ES6 method definitions: foo() {}
    'begin': '''(?x)
      (?=
        (?!
          (break|case|catch|continue|do|else|finally|for|function|if|export|
          import|package|return|switch|throw|try|while|with)
    ...
```

I believe this is what prevents the grammar from recognizing reserved words as method names. However, the ECMAScript spec is pretty clear that anywhere where one is unambiguously naming a property, reserved words are allowed as names. The spec differentiates this as being an `IdentifierName` token (context where a name is just a name, period) vs `Identifier` token (context where reserved words might be encountered and treated as such). In this case, the top-level bindings of a class are named by a `PropertyName` expression, which is defined like this:

```
PropertyName[Yield] :
  LiteralPropertyName
  ComputedPropertyName[?Yield]

LiteralPropertyName :
  IdentifierName
  StringLiteral
  NumericLiteral
```
citation: <http://www.ecma-international.org/ecma-262/6.0/#sec-object-initializer>

This is `IdentifierName`:

```
IdentifierName ::
  IdentifierStart
  IdentifierName IdentifierPart
```
citation: <http://www.ecma-international.org/ecma-262/6.0/#sec-names-and-keywords>

…which is followed by definitions that expand this out, such that it is clearly just a sequence of characters.

And looping back around, this is what defines what's allowed as a method definition:

```
MethodDefinition[Yield] :
  PropertyName[?Yield] ( StrictFormalParameters ) { FunctionBody }
  ...
```
citation: http://www.ecma-international.org/ecma-262/6.0/#sec-functions-and-classes

I hope you find this useful!
