### ISSUE TITLE
Minor variable name code highlighting bug in comment on GitHub

### ISSUE THREAD

**Issue by AndrewRayCode** [atom/language-javascript#481]
### Description

On [this seciton of GitHub Readme page](https://github.com/Jam3/math-as-code#function-notation), if you scroll down to the code block, you can see the word "a" appears to be highlighted (like a variable?) inside of the comment. But only the first one, not the second one.

![screen shot 2017-01-10 at 4 06 46 pm](https://cloud.githubusercontent.com/assets/79215/21830027/d06925f6-d74e-11e6-9bcf-00012842e4b7.png)

I suspect it's because it's a variable name used in the function definition? I would like to look into this but I wasn't able to reproduce the highlighting by pasting that code block into an empty Javascript file in Atom. Not sure how to test the grammar otherwise.

**Comment by Alhadis** [comment]
Not a bug. That's JSDoc syntax; have a look at what it matches for [`@param`](http://usejsdoc.org/tags-param.html#examples) tags, and compare that with what it matches for [`@return`](http://usejsdoc.org/tags-returns.html#examples) tags:

~~~js
/**
 * @param {Type} name Description
 * @param {Type} name - Description
 * @return {Type} description
 */
~~~

**Comment by AndrewRayCode** [comment]
oh lol. nice
