### ISSUE TITLE
Auto-Indent is misaligning JavaScript Switch statements

### ISSUE THREAD

**Issue by ChrisPearce** [atom/language-javascript#49]
The switch statement in JavaScript files is not being indented correctly.

Each case statement is aligning under the break statement directly above it, rather than aligning with the preceding case statement.

A screenshot of this is:
![javascript switch statement identing issue](https://cloud.githubusercontent.com/assets/402894/3827729/bc1a8d46-1d70-11e4-9597-3b005cc3f736.png)

**Comment by Gp2mv3** [comment]
I think work has been done on this issue because now the indentation is much slower than before... My CPU hit 100% for 5/10 seconds each time I auto-indent, even with smal files (around 300 lines).

**Comment by kurtommy** [comment]
any solution for this indentation problem?

**Comment by tdbs** [comment]
For a while i thought it was my fault, amazed this is still a bug since August.

**Comment by kurtommy** [comment]
Incredible!


Tommaso Rossi

Contacts:
Skype: kurtommyk
Mobile: 3393000359

Website:
www.rossitommaso.it

Short CV:
- Linkedin: http://goo.gl/YaokpB
- Hibryd App: Ionicframework
- FE: Angular js | Grunt | Bower | Jasmine | Karma | Protractor | HTML5 | CSS3
- BE: Laravel 5 | cakephp | Symfony | Yii



Rispetta l’ambiente. Hai davvero bisogno di stampare questa mail?
Please consider the environment – Do you really need to print this email?

Informativa Privacy - Ai sensi del D. Lgs n. 196/2003 (Codice Privacy) si precisa che le informazioni contenute in questo messaggio sono riservate e ad uso esclusivo del destinatario. Qualora il messaggio in parola Le fosse pervenuto per errore, La preghiamo di eliminarlo senza copiarlo e di non inoltrarlo a terzi, dandocene gentilmente comunicazione. Grazie.

Privacy Information - This message, for the D. Lgs n. 196/2003 (Privacy Code), may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.

**Comment by maxbrunsfeld** [comment]
Sorry this was open for so long, everyone. See the commit message above for an explanation of the new behavior.

**Comment by aniddan** [comment]
+1
