### ISSUE TITLE
Doesn't support Cocoascript syntax highlighting 

### ISSUE THREAD

**Issue by JWhiteUX** [atom/language-javascript#490]
Just chiming in. I have to change my files to `.js` extensions to highlight syntax and then back again to test them in Sketch.app

**Comment by Alhadis** [comment]
It's not JavaScript, [but JavaScript-inspired Objective-C, or something to that effect](http://developer.sketchapp.com/introduction/cocoascript/):

~~~js
var l = [a length].toString()
~~~

Good news, though: you can use the [`grammar-selector`](https://github.com/atom/grammar-selector) package (built into Atom) to specify what language a file is.

**Comment by 50Wliu** [comment]
Since Cocoascript is not JavaScript, this package will not be supporting it.

**Comment by JWhiteUX** [comment]
Thanks @Alhadis That resolved my issue.
