### ISSUE TITLE
Catastrophic backtracking in JSDoc param types

### ISSUE THREAD

**Issue by 50Wliu** [atom/language-javascript#495]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There is currently catastrophic backtracking occurring when we we fail to match the param type when multiple are present in JSDoc comments.
```js
/**
 * @param {String|String|String|String|String|String|String|String*} test 
 */
```
should be enough to reproduce.  Another example is
```js
/**
 * @param {PIXI.DisplayObject|PIXI.Container|PIXI.BaseTexture|PIXI.Texture|PIXI.Graphic*} item - Object to
 *        add to the queue
```

Thanks to @andrewstart for reporting.

### Steps to Reproduce

1. Copy/paste one of the two snippets into a new editor and set the syntax to JavaScript

**Expected behavior:** Instant highlighting

**Actual behavior:** Keep Waiting dialog

**Reproduces how often:** 100%

### Versions

language-javascript@0.126.1, but it's been happening since at least 0.122.0.

/cc @bgriffith @Alhadis

**Comment by Alhadis** [comment]
Sigh... I'll get this one (again).

**Comment by Alhadis** [comment]
FYI, the entire reason for these performance issues - and the ridiculously-contrived expressions causing them - is that nobody's bothered to structure these grammars properly.

The size of the JSDoc patterns alone suggests it's worth assigning its own grammar.

**Comment by 50Wliu** [comment]
Yeah.  The JSDoc section definitely needs to be restructured and yanked out to become its own grammar.  It's fairly impossible to see where the backtracking is occurring unlike the last one.

(Also, commas will trigger the catastrophic backtracking as well)

**Comment by Alhadis** [comment]
If I do a full rewrite, will it be worth it though?

I mean, the whole `tree-sitter` thing and all...

**Comment by 50Wliu** [comment]
That's up to you.

**Comment by Alhadis** [comment]
I'll do it to make up for the unsuccessful SassLess->CSS integration... which, BTW, will have to be limited to some unexciting pattern inclusions. I was hoping of having them share CSS's pattern-matching, but having to accommodate subtraction arithmetic between words has killed it.

This took too long because I wanted to do too much. :c

**Comment by 50Wliu** [comment]
A good first step to take is to make the capture on L2240 possessive.  That gets rid of the catastrophic bactrack error on Regex101 (back to ~1-3ms), but there's some other pattern still backtracking in Atom.

**Comment by Alhadis** [comment]
Think I'll just rewrite the whole damn JSDoc grammar myself. How's that for possessive? 💚 

Shouldn't take me more than an hour. The "language" has such an absurdly-simple composition, it's embarrassing that it could snowball into what it has... :(

**Comment by Alhadis** [comment]
I'll start once I've finished fixing file-icons/atom#550...

**Comment by Alhadis** [comment]
@50Wliu JSYK, I've tweaked the scope-names for the `/* … */` blocks; they're technically not *entirely* accurate going by @infininight's [guidelines](https://gist.github.com/infininight/9392d1e4408d507a4691e3daba9b3ec9) for `punctuation`-type scopes (which are the closest thing to authority we'll find).

If you see similar changes in future pull-requests, my recent discovery of that gist will be the reason why.

**Comment by Alhadis** [comment]
@50Wliu Can I ditch `other.meta.jsdoc` in favour of something, erh, specific? Or do you foresee changes to these scopes breaking any documentation-related Atom packages or anything?

**Comment by 50Wliu** [comment]
Can't tell you without seeing the PR first, but that does sound like a weird scope.

**Comment by Alhadis** [comment]
Well... to be honest, many of these scopes are weird. I'm keeping them for theming compatibility, but any scope that contains `other` starts looking like `deleteme` very rapidly.

I'll torch it.  Not gonna keep cargo-culted material.

**Comment by Alhadis** [comment]
> Shouldn't take me more than an hour

Okay, ignore that, because I'm spending more time reading about JSDoc features I didn't know existed than I am writing stuff (so far). I'm combing through the [official specification](http://usejsdoc.org/#block-tags) alphabetically, writing the grammar as I go along.

[You can track my progress here](https://github.com/Alhadis/MagicECMAScript).

**Comment by Alhadis** [comment]
... just letting you know [I'm done](https://github.com/Cutlery-Drawer/language-javascript/blob/jsdoc/grammars/jsdoc.cson), but I'm damned if I know how long it'll take to repair these specs. Heh.

Shouldn't take an hour...
