### ISSUE TITLE
Slow colorisation of minified file

### ISSUE THREAD

**Issue by aeschli** [atom/language-javascript#500]
Originating from https://github.com/Microsoft/vscode/issues/21860,
reproducible in Atom:

- open  https://raw.githubusercontent.com/hangxingliu/mdjs/master/mdjs.min.js in Atom
- wait ~10 seconds for colorisation to be finished

**Comment by 50Wliu** [comment]
I can't reproduce - the file tokenizes instantly for me using language-javascript@0.126.1 and 1.17.0-dev-0a6bbf0a7.
