### ISSUE TITLE
JSON.stringify() does not have the same scopes as JSON.parse()

### ISSUE THREAD

**Issue by TangSteven** [atom/language-javascript#508]
JSON.stringify() does not have the same scopes as JSON.parse()

**JSON.parse() Scopes:**
- source.js
- meta.method-call.js
- meta.arguments.js
- meta.method-call.js
- support.function.js

**JSON.stringify() Scopes:**
- source.js
- meta.method-call.js
- entity.name.function.js

### Version: 1.18.0-beta0

**Comment by thomasjo** [comment]
This issue can be resolved by adding `stringify` to [javascript.cson#L1672-L1692](https://github.com/atom/language-javascript/blob/07439aec5ec129cb356e97c95cec616a4e323c21/grammars/javascript.cson#L1672-L1692).
