### ISSUE TITLE
Failed to load a language-javascript package grammar

### ISSUE THREAD

**Issue by elyaraujo** [atom/language-javascript#518]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-javascript](https://github.com/atom/language-javascript) package 0.126.1

### Stack Trace

Failed to load a language-javascript package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-javascript\grammars\regular expression replacement (javascript).json' in C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-javascript\grammars\regular expression replacement (javascript).json

Error: ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-javascript\grammars\regular expression replacement (javascript).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-javascript/grammars/regular expression replacement (javascript).json:1:1
```

### Commands

```
```

### Non-Core Packages

```
color-picker 2.0.14 
minimap 4.19.0 
pigments 0.19.5 
```

**Comment by rsese** [comment]
Closing per https://github.com/atom/language-ruby-on-rails/issues/55#issuecomment-309392781

**Comment by Vasco10** [comment]
Just upgraded from ver. 19 to 21 (portable version), got these errors:
ENOENT: no such file or directory, open 'E:\AtomStudio\resources\app\node_modules\language-javascript\grammars\jsdoc.json' in E:\AtomStudio\resources\app\node_modules\language-javascript\grammars\jsdoc.json
Hide Stack Trace
Error: ENOENT: no such file or directory, open 'E:\AtomStudio\resources\app\node_modules\language-javascript\grammars\jsdoc.json'
  at E:\AtomStudio\resources\app\node_modules\language-javascript\grammars\jsdoc.json:1:1
-------------------------------
The error was thrown from the language-javascript package. This issue has already been reported.
==================
ENOENT: no such file or directory, open 'E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScript.json' in E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScript.json
Hide Stack Trace
Error: ENOENT: no such file or directory, open 'E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScript.json'
  at E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScript.json:1:1
------------------------------
The error was thrown from the language-typescript package. Atom is out of date: 1.19.0 installed; 1.21.0 latest. Upgrading to the latest version may fix this issue.
==================
ENOENT: no such file or directory, open 'E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScriptReact.json' in E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScriptReact.json
Hide Stack Trace
Error: ENOENT: no such file or directory, open 'E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScriptReact.json'
  at E:\AtomStudio\resources\app\node_modules\language-typescript\grammars\TypeScriptReact.json:1:1
-----------------------------------
The error was thrown from the language-typescript package. Atom is out of date: 1.19.0 installed; 1.21.0 latest. Upgrading to the latest version may fix this issue.

**Comment by adamreisnz** [comment]
I'm seeing this error constantly as well

**Comment by zap0xfce2** [comment]
Is there a solution for this error?

**Comment by rsese** [comment]
@malodie you have `language-javascript` installed as a community package, go ahead and run `apm uninstall language-javascript` and that should clear up the error you're seeing.  @zap0xfce2 are you getting the same error as first reported?

**Comment by zap0xfce2** [comment]
@rsese Thanks uninstalling the language-javascript community package fixes the error.
