### ISSUE TITLE
Faulty syntax highlighting arrow functions with long arrays of strings

### ISSUE THREAD

**Issue by louwers** [atom/language-javascript#525]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Arrow functions that return a literal expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) have bugged syntax highlighting if that expression is a long array of strings.

![screenshot_2017-08-01_10-55-10](https://user-images.githubusercontent.com/649392/28817265-ee8fd05e-76a7-11e7-8793-e828be284536.png)

### Steps to Reproduce

1. Open empty file, set syntax to Javascript.
2. Paste either code snippet:

```js
let func = idx => ["nul", "één", "twee", "drie", "vier", "vijf", "zes", "zeven","acht", "negen", "tien", "elf", "twaalf", "dertien", "veertien", "vijftien", "zestien", "zeventien", "achttien", "negentien", "twintig"][idx];
```
or

```js
{
  numberToWord: idx => ["nul", "één", "twee", "drie", "vier", "vijf", "zes", "zeven","acht", "negen", "tien", "elf", "twaalf", "dertien", "veertien", "vijftien", "zestien", "zeventien", "achttien", "negentien", "twintig"][idx]
}
```
3. Observe incorrect syntax highlighting.

**Expected behavior:** All commas have the same color. The `[idx]` part at the end does not have the same color as the strings.

**Actual behavior:** Near the end the commas as well as the `[idx]` part is recognized as part of the string.

**Reproduces how often:** Always

### Versions

```
Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

```

```
apm  1.18.3
npm  5.3.0
node 8.2.1 x64
python 2.7.13
git 2.13.3
```

Running Arch Linux.

**Comment by Alhadis** [comment]
Goeiemorgen Bert. =)

That's actually deliberate. To optimise rendering performance, Atom deliberately limits the number of tokens that can be matched per line. It was introduced in [Atom v1.15.0](https://github.com/atom/atom/releases/tag/v1.15.0).

**Tip:** You can hack the grammar at runtime using your `~/.atom/init.js` file. Here's what I used to remove the limit -

~~~js
function loadGrammar(scope){
	return new Promise(resolve => {
		const result = atom.grammars.grammarsByScopeName[scope];
		if(result) return resolve(result);
		const disposable = atom.grammars.onDidAddGrammar(grammar => {
			if(scope === grammar.scopeName){
				disposable.dispose();
				resolve(grammar);
			}
		});
	});
}

loadGrammar("source.js").then(js => js.maxTokensPerLine = 500);
~~~

(Which isn't recommended usage, BTW, but I [kinda had no choice](https://github.com/Alhadis/Roff.js/blob/master/lib/postprocessor.js#L128-L185)).

Groeten,

**Comment by louwers** [comment]
Alright, thank you for the elaborate clarification! And good evening to you. :wink:

**Comment by Alhadis** [comment]
Geen dank maat. ;)

**Comment by Alhadis** [comment]
Regarding the code, there's [plenty more where that came from](https://github.com/Alhadis/Atom-PhoenixTheme), and not all of it's bound to make sense. But you can get some inspiration from [`commands.js`](https://github.com/Alhadis/Atom-PhoenixTheme/tree/master/src/commands), I suppose. It's a personal setup, so YMMV.
