### ISSUE TITLE
Paragraph reflow does not work with old-style C comments.

### ISSUE THREAD

**Issue by alflanagan** [atom/language-javascript#531]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Reflow of a comment block delimited with one or more '//' prefixes works nicely. However, reflow of comments between '/*' and '*/' produces unexpected results.

### Steps to Reproduce

1. Open javascript file in editor.
2. Create a doc comment which is a single line much longer than the page width
3. Select the comment
4. Press ctrl-shift-q

**Expected behavior:** [What you expect to happen]

Given

```javascript
/*
 * Lorem ipsum dolor sit...
 */
```

The _ideal_ behavior would be to produce

```javascript
/*
 * Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dapibus, odio
 * a dignissim mollis, mi orci consectetur quam, id placerat metus purus vitae
 * nibh. Nam quis dictum enim. Maecenas non ligula et ipsum congue ullamcorper...
 */
```
(and it should preserve any initial '/**' sequence for doc comments, separators, etc.)

**Actual behavior:** [What actually happens]

```javascript
/*
 /* * Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dapibus,
/*
 odio a dignissim mollis, mi orci consectetur quam, id placerat metus purus
/*
 vitae nibh. Nam quis dictum enim. Maecenas non ligula et ipsum congue [...] */
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

```
$ atom --version
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.5
$ cat /etc/fedora-release 
Fedora release 26 (Twenty Six)
```

**Comment by alflanagan** [comment]
OK, this actually is not handled by this package. Will try to find the one that does...

**Comment by 50Wliu** [comment]
You're probably looking for [atom/autoflow](https://github.com/atom/autoflow).
