### ISSUE TITLE
Request: Add syntax scope hooks for ES6?

### ISSUE THREAD

**Issue by smlombardi** [atom/language-javascript#56]
As in https://github.com/Benvie/JavaScriptNext.tmLanguage for Sublime.

**Comment by Dashed** [comment]
ES6 classes: https://6to5.org/features.html#classes

Fancy coloring like CoffeeScript classes as shown in the picture here: https://github.com/kevinsawicki/monokai#monokai-theme

**Comment by Dashed** [comment]
Method definitions http://www.2ality.com/2014/12/es6-oop.html

```js
let obj = {
    myMethod(param) {
    }
};
```

**Comment by jsg2021** [comment]
+1 for ES6 :)

**Comment by mendenhallmagic** [comment]
+1, specifically for methods

**Comment by deepsweet** [comment]
https://github.com/AMalininHere/language-javascript-better

**Comment by albertorestifo** [comment]
![image](https://cloud.githubusercontent.com/assets/1037048/8581361/8d5c3c4e-25c0-11e5-8fb8-e58f8d392f7c.png)

ES6 getter and setter in Classes

**Comment by q13** [comment]
+1

**Comment by 50Wliu** [comment]
Getters/setters are the only things I can find in this issue that don't receive at least some type of highlighting.  @albertorestifo please open a new issue for that.

As this issue is pretty generic, I'm going to close this in favor of more specific ones.
