### ISSUE TITLE
Template string syntax stop working

### ISSUE THREAD

**Issue by douglasduartetb** [atom/language-javascript#572]
Hi, i update to last vesion and template strings with highlight stop working.

![39085555-bfa07528-455a-11e8-9405-8553811a0f49](https://user-images.githubusercontent.com/7443043/39203824-53fc6d30-47cc-11e8-9b15-964d8477b21d.png)

Version: 1.26.0 x64, windows 7

**Comment by Arcanemagus** [comment]
@maxbrunsfeld This looks to be a regression after enabling `tree-sitter-javascript`, as it seems that currently doesn't bring in HTML to parse this string like the TextMate grammar looks to be:

TextMate:
![image](https://user-images.githubusercontent.com/427137/39217837-98928de4-47d6-11e8-8f80-ea410c0f9375.png)

Tree-sitter:
![image](https://user-images.githubusercontent.com/427137/39217858-ab8571be-47d6-11e8-8db5-9085c3fc3227.png)

Raw text:
```js
let template = html`
<div>
  <textarea></textarea>
</div>`;
```

----

@douglasduartetb Thanks for filing this issue, for future reference please fill out the template completely, thanks!

If you need these strings to be highlighted as HTML for now you can disable the experimental Tree-sitter parsers.

**Comment by maxbrunsfeld** [comment]
Yeah, the Tree-sitter JavaScript parser currently doesn't have this behavior, thought it is something we could add in the future.

**Comment by maxbrunsfeld** [comment]
This is now implemented.
