### ISSUE TITLE
[FEATURE] Support apidoc highlighting

### ISSUE THREAD

**Issue by almic** [atom/language-javascript#579]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I was finding no luck with creating a good api documentation in my Express application using JSDoc. So I did some searching and found apidoc. I've already started writing grammar for it, and realized that if i want to use it, I'd have to include the entire grammar for javascript. Perhaps this is more related to the problem that extending a language is impossible without changing the whole file grammar to your extension, rather than allowing the language "Javascript" to include your extension package.

apidoc shares no tags with the existing JSDoc (except `@api`, but that isn't even a JSDoc tag, according to http://usejsdoc.org/)

### Steps to ~Reproduce~ Implement

1. Write the grammar for apidoc
2. Include that inside `language-javascript`, just like `jsdoc.cson` is
3. Add options to enable highlighting (perhaps disabled by default, but maybe not?)

**Expected behavior:** Includes nice highlighting for apidoc blocks, without stomping on JSDoc (which is really won't)

### Additional Information

I'm already working on the grammar, and expect to finish very soon. I opened this issue to hopefully get some feedback before I open a pull request. Since this is a core package, I really don't want to embarrass myself by submitting a PR that literally would have never been accepted if some internal stuff wouldn't allow it.

Also, there is a snippets package for this, but that is way different from grammar. I couldn't find this anywhere on at least the first few pages when searching `apidoc`

**Comment by almic** [comment]
Just discovered `injectionSelector`, sucks that Atom doesn't have any mention of it in their own tutorial!

**Comment by 50Wliu** [comment]
> sucks that Atom doesn't have any mention of it in their own tutorial!

Yeah, sorry about that 😬.  Haven't managed to fill in that portion yet.
