### ISSUE TITLE
Atom not handling multi-line strings correctly

### ISSUE THREAD

**Issue by Cydrobolt** [atom/language-javascript#58]
In Javascript, each line in a multi-line string must be ended with a `\`. Atom does not recognise this need, and highlights the whole string rather than warning users about missing `\`s.

**Comment by oferh** [comment]
+1

**Comment by rossPatton** [comment]
wouldn't be something that your linter would catch? i know eslint yells at you for this

**Comment by 50Wliu** [comment]
Fixed by #209.
