### ISSUE TITLE
[tree-sitter] Incorrect parsing, highlight

### ISSUE THREAD

**Issue by t9md** [atom/language-javascript#595]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With tree-sitter enabled, it shows incorrect highlight in specific file.

### Steps to Reproduce

1. Enable tree-sitter parser, open editor and paste [this code](https://raw.githubusercontent.com/t9md/atom-vim-mode-plus/d8e38e3cc7a5984fcc9ebdd4fbe083ce5aff6a9f/lib/text-object.js) and set it's grammar to JavaScript.
2. You see odd syntax color and odd result of "Scope at Cursor"(`alt-cmd-p`).

Odd parsing state seem to become recovered after line 592.

<img width="713" alt="text-object_js_ ___github_atom-vim-mode-plus_and_1__zsh" src="https://user-images.githubusercontent.com/155205/45386054-5cc5bd00-b64d-11e8-96d5-2b0ce1fa8e00.png">

**Expected behavior:** [What you expect to happen]

Correct parsing, syntax highlight. It's not happening in TextMate language-mode.

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

latest master and beta below
```
Atom    : 1.31.0-beta1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
Atom    : 1.32.0-dev-76cdeae4a
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by maxbrunsfeld** [comment]
Are you using windows (CRLF line ending)? It looks like there's a bug in how we're handling those line endings. Thanks for the report.

**Comment by t9md** [comment]
No, just LF.

**Comment by t9md** [comment]
This is a smaller set of code I can reproduce odd parsing state.
`curstructor()` 's `return 'foo'` part is necessary to repro.
If you started with `return /{$/` commented out, parsing is OK then comment-in to get it wrong.

```javascript
class ClassName {
  constructor () {
    return 'foo'
  }
  meth(scopeName) {
    if (scopeName === "bar") {
      return "baz"
    } else {
      return /{$/
    }
  }
}
```

**Comment by maxbrunsfeld** [comment]
Wow that was really bad. It was a combination of a regex parser bug (it currently doesn't handle the regex `{$`) and a bug in Tree-sitter itself. Thanks so much for the minimal repro.

**Comment by t9md** [comment]
Thanks for the quick fix.
Maybe this is accidental close?
Still, the package.json need to be updated to newer tree-sitter which includes the fix.

**Comment by t9md** [comment]
Ok, thanks for the clarification.
