### ISSUE TITLE
Tree-sitter won't allow single-line comment block folding

### ISSUE THREAD

**Issue by jbrew138** [atom/language-javascript#607]
*Edit by @rsese: x-ref same (?) issue for Go https://github.com/atom/language-go/issues/165*

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After updating to Atom 1.32.0, single line comment blocks ("//") over multiple lines can no longer be folded, manually or using folding from the edit menu. Multi-line comments ("/* ... */") can still be folded.

I assume it's related to the new tree-sitter setting that was enabled by default starting with the latest version. Disabling "Use Tree Sitter Parsers" restores the old behavior, and the single-line comment blocks can be folded again. The same goes when running in safe mode as well.

I'm not aware if this is the new behavior intended with the new tree-sitter grammar, so I'm reporting it as a bug.

### Versions

Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
Windows: 10 Pro, v1709 16299.547

**Comment by rsese** [comment]
Thanks for the report! With Tree-sitter enabled, I see the behavior you described on macOS 10.12.6 and 1.34.0-nightly0 with:

```js
// hello
// world
```

Not sure if it's intentional either, we'll ask the team to take a look.  Also /cc @maxbrunsfeld as a heads up :v:

**Comment by calebmeyer** [comment]
Same issue in ruby as well. I assume this is affecting all languages. Unfortunately, not equally, as some languages have multi-line comments and frequently use them while others don't. Ruby has a way to do multi-line comments, but the linter discourages it, favoring using `#` everywhere.

**Comment by rsese** [comment]
Thanks again for the report - since this affects multiple languages, we created an issue in atom/atom for tracking if you want to subscribe there:

https://github.com/atom/atom/issues/18549
