### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by AlanSean** [atom/language-javascript#609]
You have the core package "language-javascript" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:11:176134)
Generator.next (null:null:null)
step (<embedded>:11:175970)
<unknown> (null:null:null)
process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by Ben3eeE** [comment]
Please follow the instructions listed in your issue.
