### ISSUE TITLE
Tree-sitter regexp delimiters parsed incorrectly

### ISSUE THREAD

**Issue by dwelle** [atom/language-javascript#613]
### Prerequisites

* [x] Reproduced the problem in Safe Mode
* [x] Checked that your issue isn't already filed

### Description

Opening/closing `/` regex delimiter not parsed correctly.

### Steps to Reproduce

```
/^[a]*$/
```
**Expected behavior:**

Should have `syntax--begin`/`syntax--end` classes.

![image](https://user-images.githubusercontent.com/5153846/47616291-01477580-dabb-11e8-9066-2c1093d1b932.png)

**Actual behavior:** [What actually happens]

![image](https://user-images.githubusercontent.com/5153846/47616263-aa41a080-daba-11e8-9c9a-4bcad3357599.png)

![image](https://user-images.githubusercontent.com/5153846/47616259-a4e45600-daba-11e8-81dc-17823fad4c8f.png)

### Versions

- atom 1.32.0 x64
- win 7

**Comment by rsese** [comment]
Thanks for the report!  Reproduced on macOS 10.12.6 with 1.34.0-nightly5.

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed on the latest version of atom https://github.com/atom/atom/releases/tag/v1.56.0
