### ISSUE TITLE
RegExp contents are not highlighted

### ISSUE THREAD

**Issue by RomanFro** [atom/language-javascript#627]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

RegExp contents are not highlighted in switch.

### Code to reproduce

```js
'use strict';

switch (true) {
    case /^hello$/.test('hello'): {
        console.log('world');
    }
}

```

**Expected behavior:** Nice highlighting.

**Actual behavior:** RegExp contents are not highlighted.

**Reproduces how often:** 100%

### Versions

Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify, do you have Tree-sitter enabled (the setting is `Settings > Core > Enable Tree Sitter Parsers`) and can you share a screenshot of what you see in Atom?  Also, can you update to the latest hotfix release (currently 1.32.2) and let us know if you still see the same issue?

This is what I see in 1.32.2:

![regex-js](https://github-slack.s3.amazonaws.com/monosnap/Project__sandboxtest-tree-sitter_2018-11-14_13-05-51.png)

**Comment by RomanFro** [comment]
@rsese tree-sitter was disabled because of #600. When I enabled it - highlighting started to work normally.
