### ISSUE TITLE
CSS grammar not injected for custom styled-components

### ISSUE THREAD

**Issue by edahlseng** [atom/language-javascript#634]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The CSS grammar is not properly injected for styled-components using custom components.

### Steps to Reproduce

The following correctly syntax highlights:
```js
const TestComponent = styled.div`
	h1 {
		color: green;
	}
`;
```

![image](https://user-images.githubusercontent.com/6352776/51214824-e0c9d300-18d3-11e9-84d1-042a8409bcc3.png)

The following does not correctly syntax highlight:

```js
const TestComponent = styled(UnstyledComponent)`
	h1 {
		color: green;
	}
`;
```

![image](https://user-images.githubusercontent.com/6352776/51214770-bd068d00-18d3-11e9-9de8-d85faf1c5c33.png)

### Versions

```
$ atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15
git 2.20.1
```

**Comment by rsese** [comment]
Thanks @edahlseng - confirmed on macOS 10.12.6 with 1.34.0:

![correct](https://github-slack.s3.amazonaws.com/monosnap/test.js__worktest-tree-sitter_2019-01-17_16-00-10.png)

![incorrect](https://github-slack.s3.amazonaws.com/monosnap/test.js__worktest-tree-sitter_2019-01-17_16-01-01.png)
