### ISSUE TITLE
use improved for loop

### ISSUE THREAD

**Issue by Ali-00-Ridha** [atom/language-javascript#636]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

this atom extension/package uses the old for loop:
for (var i = 0; i < array.length; i++) {
  array[i]
}

Another option is Insert improved for loop like this:
for (var i = array.length - 1; i >= 0; i--){
  array[i]
};

### Steps to Reproduce

1. open .js file
2. type (for)
3. from keyboard press (tab)

**Expected behavior:**
expecting the improved for loop:
for (var i = 0; i < array.length; i++) {
  array[i]
}

**Actual behavior:** 
old bad/overhead for loop code:
for (var i = 0; i < array.length; i++) {
  array[i]
}

**Reproduces how often:** 100% of the time

### Versions

latest atom version 
Atome: 1.34.0 x64
Electron: 2.0.16
Chrome: 61.0.3163.100
Node: v8.9.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for contributing @Ali-00-Ridha!  As detailed in https://github.com/atom/language-javascript/pull/637#issuecomment-456902494, we're going to keep things as is for now so we'll go ahead and close this issue too.
