### ISSUE TITLE
JSDoc/Doc Block tab complete breaks highlighting

### ISSUE THREAD

**Issue by jchook** [atom/language-javascript#660]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When using the tab-completion to initiate a "doc block" style comment, the grammar parser gets very confused and labels code immediately outside of the comment as `.comment.block`.

This screenshot from safe mode:

![image](https://user-images.githubusercontent.com/193530/65819960-2c69a600-e1f1-11e9-89e7-29a80668f4d0.png)

This video from my normal atom env illustrates the problem more clearly:

![Peek 2019-09-28 13-18 weird highlighting](https://user-images.githubusercontent.com/193530/65820055-8b7bea80-e1f2-11e9-8191-63d711654b30.gif)

### Steps to Reproduce

1. Create a new JavaScript file, using the built-in JS grammar
2. Write some JS code
3. Add a doc block comment to the lower part of the code via <kbd>/</kbd> <kbd>&#42;</kbd> <kbd>&#42;</kbd> <kbd>TAB</kbd>
4. Add a doc block comment to the upper part of the code via <kbd>/</kbd> <kbd>&#42;</kbd> <kbd>&#42;</kbd> <kbd>TAB</kbd>

**Expected behavior:**

Correct syntax highlighting

**Actual behavior:**

The JS grammar labels the JS code immediately below the upper block comment as part of the comment block.

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

**Comment by rsese** [comment]
Thanks for the report - just to double check this isn't related to a recently fixed issue, can you confirm if you see this problem in the latest beta (currently [1.41.0-beta1](https://github.com/atom/atom/releases/tag/v1.41.0-beta1))?

**Comment by jchook** [comment]
@rsese excellent spidey senses on that. Atom 1.41.0-beta1 does not have the same issue.
