### ISSUE TITLE
Array with optional chanining

### ISSUE THREAD

**Issue by ChingChang9** [atom/language-javascript#688]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

[Array access with optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Array_item_access_with_optional_chaining) is not recognized as a value in objects. Optional chaining with array outside of an object works, but when used directly inside an object as a value, the next key isn't highlighted. If it is the first key-value pair of the object, both the key following it and its own key would not be highlighted

![atom language-javascript bug for array optional chaining](https://user-images.githubusercontent.com/38874004/103148418-6051b500-472d-11eb-9a98-9490a614a3b0.png)

### Steps to Reproduce

1. Open a javascript file
2. Write a key-value pair with a value using array optional chaining
3. Add another key-value pair before and after the key-value pair with array optional chaining
4. Delete the key-value pair before the one with array optional chaining

**Expected behavior:**

The keys of the object should be highlighted in both step 3 and 4

**Actual behavior:**

The key after the one with array optional chaining isn't highlighted in step 3
Both the key after and the key of the one with array optional chaining aren't highlighted in step 4

**Reproduces how often:**

Always

### Versions

Atom: 1.53.0
OS: macOS Catalina Version 0.15.6 (19G73)

**Comment by icecream17** [comment]
All optional chaining variants aren't supported unfortunately - issue #640 is similar
veitbajarsch in that forum suggested to install language-babel to fix the problem

**Comment by ChingChang9** [comment]
Thanks for the suggestion. I've installed it, restarted atom, and tried it in safe mode. Unfortunately, the error is still there. Is there a certain setting that I need to change in `language-babel` after installation?

**Comment by icecream17** [comment]
I don't know, I haven't tried it, however I found https://github.com/gandm/language-babel/issues/510, maybe that could help?

**Comment by ChingChang9** [comment]
Thanks. Closing this because it seems to be a similar issue.
