### ISSUE TITLE
Over-enthusiastic outdent of curly braces

### ISSUE THREAD

**Issue by jbt** [atom/language-javascript#77]
A gif probably explains it best:

![outdent2](https://cloud.githubusercontent.com/assets/120506/5451371/78d8b932-8507-11e4-8434-23ae2691eb63.gif)

Firstly, I'd contend that the `])` shouldn't be automatically indented, but I can live with that.

Main point: the `{whatever}` line automatically outdents as soon as I type the first `{` (presumably because it thinks it's opening a block rather than an object), and then continually tries to outdent whenever I type any more characters on the line (the re-indentation in the gif is me hitting `ctrl+]`)

Been happening in `atom --safe` built off master for the last couple of days, presumably since the update to language-javascript@0.51 in relation to e38f1cd9eddea7cb9994342ca9bceef2a4e3d7ff

**Comment by joshthecoder** [comment]
Yeah been seeing this as well and it's become pretty annoying. Every change in the object literal causes it to shift it back to the left. :(

**Comment by joshthecoder** [comment]
Reverting e38f1cd locally fixes the issue for now. Not 100% sure yet what the proper fix is for this issue.

**Comment by AgentME** [comment]
If something causes me to stop using Atom, it's going to be this issue. I've had to fight Atom trying to unindent my code several times everyday. Is this issue not reproduce-able for everyone?

**Comment by afanasy** [comment]
It is reproducible and very annoying, it is something wrong with indent patterns here:
https://github.com/atom/language-javascript/blob/master/settings/language-javascript.cson

**Comment by UltimateBrent** [comment]
For anyone who can't wait on a full patch:
* open up your language-javascript package
* view code
* open `settings/language-javascript.json`
* remove ` | ^ \\s* \\{ ` from the descreaseIndentPattern line. It should end up as `"decreaseIndentPattern": "(?x) ^ \\s* (\\s* /[*] .* [*]/ \\s*)* [})]"`
