### ISSUE TITLE
Function references are highlighted incorrectly

### ISSUE THREAD

**Issue by neftaly** [atom/language-javascript#90]
Function references beginning with the word "function" are highlighted incorrectly. The text "function" is highlighted inappropriately.

For example:
```javascript
lambdas = functional(programming);
```

**Comment by 50Wliu** [comment]
What language is this?  Can you create an issue on the corresponding language package?  You can find the complete list of core packages [here](https://github.com/atom).

**Comment by neftaly** [comment]
This is in JavaScript. Is this not the correct repo? I've been following the rabbit-hole several levels down from GH-flavoured MD JS parsing.

**Comment by 50Wliu** [comment]
Nevermind...thought this was on the main atom/atom repository.  My mistake, sorry.

**Comment by kevinsawicki** [comment]
Fixed by #103
