### ISSUE TITLE
Some properties are marked as constants

### ISSUE THREAD

**Issue by nevir** [atom/language-javascript#97]
`thing.length`, `thing.className`, etc. Feels really awkward for highlighting

At the very least, it would be handy to mark them as `.property` in addition to their other classes. Would help disambiguate

**Comment by AMalininHere** [comment]
Hello! You can just use https://atom.io/packages/language-javascript-better which highlights each identifier after dot as object's property.

**Comment by code-tree** [comment]
I'm getting a bit confused when things like "thing.content" is tagged as ".support.constant.dom" and then trying to work out if I'm overriding some built-in property or method?

In this case, shouldn't it just be "window.content" that is tagged?

**Comment by 50Wliu** [comment]
They're now tokenized as `support.variable.property.js`, closing.
